import type { Language } from "./i18n";

export interface CyFunControl {
  id: string;
  category: "ID" | "PR" | "DE" | "RS" | "RC";
  subcategory: string;
  nl: string;
  en: string;
  fr: string;
  /** One-line practical explanation */
  hint_nl: string;
  hint_en: string;
  hint_fr: string;
  /** Optional short example table/text */
  example_nl?: string;
  example_en?: string;
  example_fr?: string;
  /** Roadmap step indices (0-based) this control maps to */
  steps: number[];
}

export const CYFUN_CATEGORIES: Record<string, { nl: string; en: string; fr: string; color: string }> = {
  ID: { nl: "Identificeren", en: "Identify", fr: "Identifier", color: "bg-blue-600" },
  PR: { nl: "Beschermen", en: "Protect", fr: "Protéger", color: "bg-green-600" },
  DE: { nl: "Detecteren", en: "Detect", fr: "Détecter", color: "bg-yellow-600" },
  RS: { nl: "Reageren", en: "Respond", fr: "Répondre", color: "bg-orange-600" },
  RC: { nl: "Herstellen", en: "Recover", fr: "Récupérer", color: "bg-red-600" },
};

export const CYFUN_CONTROLS: CyFunControl[] = [
  // ===== IDENTIFICEREN (ID) =====
  // Asset Management
  { id: "ID.AM-1", category: "ID", subcategory: "AM", steps: [0],
    nl: "Inventarisatie van de binnen de organisatie gebruikte fysieke apparaten en systemen.",
    en: "Inventory of physical devices and systems used within the organization.",
    fr: "Inventaire des appareils physiques et systèmes utilisés au sein de l'organisation.",
    hint_nl: "Bijv. een lijst van alle laptops, servers, routers, printers met serienummers en locatie.",
    hint_en: "E.g. maintain a list of all laptops, servers, routers, printers with serial numbers and location.",
    hint_fr: "P.ex. tenir une liste de tous les laptops, serveurs, routeurs, imprimantes avec numéros de série et emplacement." },
  { id: "ID.AM-2", category: "ID", subcategory: "AM", steps: [0],
    nl: "Inventarisatie van de binnen de organisatie gebruikte softwareplatforms en -toepassingen.",
    en: "Inventory of software platforms and applications used within the organization.",
    fr: "Inventaire des plateformes logicielles et applications utilisées au sein de l'organisation.",
    hint_nl: "Bijv. een overzicht van alle software, licenties, versies en op welke toestellen ze draaien.",
    hint_en: "E.g. an overview of all software, licenses, versions and on which devices they run.",
    hint_fr: "P.ex. un aperçu de tous les logiciels, licences, versions et sur quels appareils ils fonctionnent." },
  { id: "ID.AM-3", category: "ID", subcategory: "AM", steps: [0],
    nl: "De organisatorische communicatie- en gegevensstromen worden in kaart gebracht.",
    en: "Organizational communication and data flows are mapped.",
    fr: "Les flux de communication et de données organisationnels sont cartographiés.",
    hint_nl: "Teken uit hoe data stroomt: van klant naar server, naar cloud, naar backup, enz.",
    hint_en: "Map out how data flows: from client to server, to cloud, to backup, etc.",
    hint_fr: "Cartographiez comment les données circulent : du client au serveur, au cloud, aux sauvegardes, etc." },
  { id: "ID.AM-4", category: "ID", subcategory: "AM", steps: [0],
    nl: "Externe informatiesystemen worden gecatalogiseerd.",
    en: "External information systems are catalogued.",
    fr: "Les systèmes d'information externes sont catalogués.",
    hint_nl: "Bijv. alle SaaS-diensten, cloud-providers en externe API's die je organisatie gebruikt.",
    hint_en: "E.g. all SaaS services, cloud providers and external APIs your organization uses.",
    hint_fr: "P.ex. tous les services SaaS, fournisseurs cloud et API externes utilisés par votre organisation." },
  { id: "ID.AM-5", category: "ID", subcategory: "AM", steps: [0],
    nl: "Middelen worden geprioriteerd op basis van hun classificatie, kriticiteit en bedrijfswaarde.",
    en: "Resources are prioritized based on their classification, criticality, and business value.",
    fr: "Les ressources sont priorisées en fonction de leur classification, criticité et valeur métier.",
    hint_nl: "Bepaal welke systemen essentieel zijn: wat mag nooit uitvallen vs. wat kan even wachten?",
    hint_en: "Determine which systems are essential: what can never go down vs. what can wait?",
    hint_fr: "Déterminez quels systèmes sont essentiels : lesquels ne peuvent jamais tomber en panne ?" },
  { id: "ID.AM-6", category: "ID", subcategory: "AM", steps: [0, 4],
    nl: "Rollen, verantwoordelijkheden en bevoegdheden op het gebied van cyberbeveiliging worden vastgesteld.",
    en: "Cybersecurity roles, responsibilities, and authorities are established for all personnel.",
    fr: "Les rôles, responsabilités et autorités en cybersécurité sont établis pour tout le personnel.",
    hint_nl: "Wie is verantwoordelijk voor IT-security? Wie meldt incidenten? Leg dit vast in een RACI-matrix.",
    hint_en: "Who is responsible for IT security? Who reports incidents? Document this in a RACI matrix.",
    hint_fr: "Qui est responsable de la sécurité IT ? Qui signale les incidents ? Documentez dans une matrice RACI." },

  // Business Environment
  { id: "ID.BE-1", category: "ID", subcategory: "BE", steps: [1],
    nl: "De rol van de organisatie in de toeleveringsketen wordt vastgesteld en gecommuniceerd.",
    en: "The organization's role in the supply chain is identified and communicated.",
    fr: "Le rôle de l'organisation dans la chaîne d'approvisionnement est identifié et communiqué.",
    hint_nl: "Breng je toeleveringsketen in kaart (wie levert aan jou, aan wie lever jij) en leg beveiligingsverantwoordelijkheden vast in contracten en SLA's.",
    hint_en: "Map your supply chain (who supplies you, who you supply) and formalize security responsibilities in contracts and SLAs.",
    hint_fr: "Cartographiez votre chaîne (qui vous fournit, à qui vous fournissez) et formalisez les responsabilités sécurité dans les contrats et SLA.",
    example_nl: "Bv. 'Wij zijn klant van Microsoft 365 voor e-mail en opslag — zij zorgen voor patches en uptime (SLA 99,9%). Onze IT-partner beheert onze servers — incident-melding binnen 24u, MFA verplicht.' Maak zo'n lijstje per leverancier.",
    example_en: "E.g. 'We are a customer of Microsoft 365 for email and storage — they handle patches and uptime (SLA 99.9%). Our IT partner manages our servers — incident notification within 24h, MFA required.' Make such a list per supplier.",
    example_fr: "Ex. 'Nous sommes client de Microsoft 365 pour l'e-mail et le stockage — ils gèrent les correctifs et la disponibilité (SLA 99,9%). Notre partenaire IT gère nos serveurs — notification d'incident sous 24h, MFA obligatoire.' Faites une telle liste par fournisseur." },
  { id: "ID.BE-2", category: "ID", subcategory: "BE", steps: [1],
    nl: "De plaats van de organisatie in de kritieke infrastructuur wordt vastgesteld.",
    en: "The organization's place in critical infrastructure is identified and communicated.",
    fr: "La place de l'organisation dans l'infrastructure critique est identifiée et communiquée.",
    hint_nl: "Bepaal of je diensten levert aan sectoren die onder NIS2 als essentieel worden beschouwd.",
    hint_en: "Determine if you provide services to sectors considered essential under NIS2.",
    hint_fr: "Déterminez si vous fournissez des services à des secteurs considérés essentiels sous NIS2.",
    example_nl: "Bv. 'Wij leveren IT-diensten aan een ziekenhuis (essentiële sector) en aan retailbedrijven (niet-essentieel). Daardoor vallen wij als belangrijke entiteit onder NIS2.' Controleer de NIS2-sectorenlijst.",
    example_en: "E.g. 'We provide IT services to a hospital (essential sector) and retail companies (non-essential). This makes us an important entity under NIS2.' Check the NIS2 sectors list.",
    example_fr: "Ex. 'Nous fournissons des services IT à un hôpital (secteur essentiel) et à des commerces (non-essentiel). Cela fait de nous une entité importante sous NIS2.' Vérifiez la liste des secteurs NIS2." },
  { id: "ID.BE-3", category: "ID", subcategory: "BE", steps: [1],
    nl: "Prioriteiten m.b.t. missie, doelstellingen en activiteiten worden vastgesteld.",
    en: "Priorities for mission, objectives, and activities are established and communicated.",
    fr: "Les priorités relatives à la mission, objectifs et activités sont établies et communiquées.",
    hint_nl: "Definieer je kernprocessen: welke bedrijfsactiviteiten mogen nooit stilvallen?",
    hint_en: "Define your core processes: which business activities can never be interrupted?",
    hint_fr: "Définissez vos processus clés : quelles activités ne peuvent jamais être interrompues ?",
    example_nl: "Bv. 'Onze facturatie en klantenportaal mogen nooit langer dan 4 uur offline zijn. Interne wiki is minder kritiek — mag 24u duren.' Maak een lijstje van je top-5 processen met prioriteit.",
    example_en: "E.g. 'Our invoicing and client portal can never be offline for more than 4 hours. Internal wiki is less critical — 24h is acceptable.' List your top-5 processes with priority.",
    example_fr: "Ex. 'Notre facturation et portail client ne peuvent jamais être hors ligne plus de 4h. Le wiki interne est moins critique — 24h acceptable.' Listez vos 5 processus principaux par priorité." },
  { id: "ID.BE-4", category: "ID", subcategory: "BE", steps: [1],
    nl: "Afhankelijkheden en kritieke functies voor levering van kritieke diensten zijn vastgesteld.",
    en: "Dependencies and critical functions for delivery of critical services are established.",
    fr: "Les dépendances et fonctions critiques pour la fourniture de services critiques sont établies.",
    hint_nl: "Breng in kaart: van welke leveranciers, systemen of personen ben je afhankelijk voor je diensten?",
    hint_en: "Map out: which suppliers, systems or people do you depend on for your services?",
    hint_fr: "Identifiez : de quels fournisseurs, systèmes ou personnes dépendez-vous pour vos services ?",
    example_nl: "Bv. 'Zonder onze internetverbinding (Proximus) kunnen we niet factureren. Zonder onze boekhouder geen BTW-aangiftes. Als Jan (sysadmin) uitvalt, kan niemand anders bij de servers.' Noteer deze afhankelijkheden.",
    example_en: "E.g. 'Without our internet connection (ISP) we can't invoice. Without our accountant, no VAT filings. If Jan (sysadmin) is unavailable, no one else can access the servers.' Document these dependencies.",
    example_fr: "Ex. 'Sans notre connexion internet (FAI), pas de facturation. Sans notre comptable, pas de déclarations TVA. Si Jan (admin) est absent, personne d'autre n'accède aux serveurs.' Documentez ces dépendances." },
  { id: "ID.BE-5", category: "ID", subcategory: "BE", steps: [1],
    nl: "Weerbaarheidsvereisten ter ondersteuning van kritieke diensten worden vastgesteld.",
    en: "Resilience requirements to support delivery of critical services are established.",
    fr: "Les exigences de résilience pour la fourniture de services critiques sont établies.",
    hint_nl: "Stel vast: hoe snel moet een dienst hersteld zijn na een incident? (RPO/RTO doelen)",
    hint_en: "Determine: how quickly must a service be restored after an incident? (RPO/RTO targets)",
    hint_fr: "Déterminez : en combien de temps un service doit-il être restauré après un incident ? (RPO/RTO)",
    example_nl: "Bv. 'Ons klantenportaal moet binnen 4u terug online zijn (RTO). We mogen max 1u aan data verliezen (RPO). E-mail mag 24u duren.' Stel dit per kritiek systeem vast en bespreek met je IT-partner.",
    example_en: "E.g. 'Our client portal must be back online within 4h (RTO). We can lose max 1h of data (RPO). Email can wait 24h.' Define this per critical system and discuss with your IT partner.",
    example_fr: "Ex. 'Notre portail client doit être rétabli sous 4h (RTO). Perte de données max 1h (RPO). L'e-mail peut attendre 24h.' Définissez ceci par système critique avec votre partenaire IT." },

  // Governance
  { id: "ID.GV-1", category: "ID", subcategory: "GV", steps: [1, 2],
    nl: "Het cyberbeveiligingsbeleid van de organisatie wordt vastgesteld en gecommuniceerd.",
    en: "The organization's cybersecurity policy is established and communicated.",
    fr: "La politique de cybersécurité de l'organisation est établie et communiquée.",
    hint_nl: "Schrijf een informatieveiligheidsbeleid en zorg dat elke medewerker dit kent en ondertekent.",
    hint_en: "Write an information security policy and ensure every employee knows and signs it.",
    hint_fr: "Rédigez une politique de sécurité de l'information et assurez-vous que chaque employé la connaît." },
  { id: "ID.GV-3", category: "ID", subcategory: "GV", steps: [1, 2],
    nl: "Wettelijke en regelgevende voorschriften inzake cyberbeveiliging worden begrepen en beheerd.",
    en: "Legal and regulatory cybersecurity requirements, including privacy obligations, are understood and managed.",
    fr: "Les exigences légales et réglementaires en cybersécurité, y compris la vie privée, sont comprises et gérées.",
    hint_nl: "Ken je verplichtingen: NIS2, GDPR, sectorale regelgeving. Houd een register van toepasselijke wetgeving bij.",
    hint_en: "Know your obligations: NIS2, GDPR, sector regulations. Maintain a register of applicable legislation.",
    hint_fr: "Connaissez vos obligations : NIS2, RGPD, réglementations sectorielles. Tenez un registre de la législation applicable." },
  { id: "ID.GV-4", category: "ID", subcategory: "GV", steps: [1],
    nl: "Governance- en risicobeheerprocessen adresseren risico's m.b.t. cyberbeveiliging.",
    en: "Governance and risk management processes address cybersecurity risks.",
    fr: "Les processus de gouvernance et de gestion des risques abordent les risques de cybersécurité.",
    hint_nl: "Neem cyberrisico's op in je bedrijfsbrede risicomanagement, niet alleen als IT-kwestie.",
    hint_en: "Include cyber risks in your enterprise-wide risk management, not just as an IT issue.",
    hint_fr: "Intégrez les cyber-risques dans votre gestion des risques à l'échelle de l'entreprise." },

  // Risk Assessment
  { id: "ID.RA-1", category: "ID", subcategory: "RA", steps: [1],
    nl: "Kwetsbaarheden van activa worden vastgesteld en gedocumenteerd.",
    en: "Asset vulnerabilities are identified and documented.",
    fr: "Les vulnérabilités des actifs sont identifiées et documentées.",
    hint_nl: "Scan regelmatig je systemen op zwakke plekken en documenteer bekende kwetsbaarheden.",
    hint_en: "Regularly scan your systems for weaknesses and document known vulnerabilities.",
    hint_fr: "Analysez régulièrement vos systèmes pour détecter les faiblesses et documentez les vulnérabilités connues." },
  { id: "ID.RA-2", category: "ID", subcategory: "RA", steps: [1],
    nl: "Informatie over cyberdreigingen wordt ontvangen van fora en bronnen voor informatie-uitwisseling.",
    en: "Cyber threat intelligence is received from information sharing forums and sources.",
    fr: "Les renseignements sur les cybermenaces sont reçus de forums et sources de partage d'informations.",
    hint_nl: "Abonneer je op CCB-waarschuwingen, CVE-feeds of CERT-meldingen om op de hoogte te blijven van dreigingen.",
    hint_en: "Subscribe to CCB alerts, CVE feeds or CERT notices to stay informed about threats.",
    hint_fr: "Abonnez-vous aux alertes CCB, flux CVE ou notifications CERT pour rester informé des menaces." },
  { id: "ID.RA-5", category: "ID", subcategory: "RA", steps: [1],
    nl: "Bedreigingen, kwetsbaarheden, waarschijnlijkheden en gevolgen worden gebruikt om het risico te bepalen.",
    en: "Threats, vulnerabilities, likelihoods, and impacts are used to determine risk.",
    fr: "Les menaces, vulnérabilités, probabilités et impacts sont utilisés pour déterminer le risque.",
    hint_nl: "Maak een risicoanalyse: kans × impact per dreiging. Gebruik een eenvoudige risicomatrix.",
    hint_en: "Perform a risk analysis: likelihood × impact per threat. Use a simple risk matrix.",
    hint_fr: "Réalisez une analyse de risques : probabilité × impact par menace. Utilisez une matrice de risques simple." },
  { id: "ID.RA-6", category: "ID", subcategory: "RA", steps: [1],
    nl: "Respons op risico's worden vastgesteld en geprioriteerd.",
    en: "Risk responses are identified and prioritized.",
    fr: "Les réponses aux risques sont identifiées et priorisées.",
    hint_nl: "Beslis per risico: accepteren, mitigeren, overdragen (verzekering) of vermijden.",
    hint_en: "Decide per risk: accept, mitigate, transfer (insurance) or avoid.",
    hint_fr: "Décidez par risque : accepter, atténuer, transférer (assurance) ou éviter." },

  // Risk Management Strategy
  { id: "ID.RM-1", category: "ID", subcategory: "RM", steps: [1],
    nl: "Risicobeheerprocessen worden vastgesteld, beheerd en goedgekeurd door belanghebbenden.",
    en: "Risk management processes are established, managed, and agreed upon by stakeholders.",
    fr: "Les processus de gestion des risques sont établis, gérés et approuvés par les parties prenantes.",
    hint_nl: "Zorg dat het management de risicoaanpak formeel goedkeurt en ondersteunt.",
    hint_en: "Ensure management formally approves and supports the risk approach.",
    hint_fr: "Assurez-vous que la direction approuve et soutient formellement l'approche des risques." },
  { id: "ID.RM-2", category: "ID", subcategory: "RM", steps: [1],
    nl: "De risicotolerantie van de organisatie wordt bepaald en duidelijk uitgedrukt.",
    en: "The organization's risk tolerance is determined and clearly expressed.",
    fr: "La tolérance au risque de l'organisation est déterminée et clairement exprimée.",
    hint_nl: "Definieer hoeveel risico acceptabel is: bijv. max 4 uur downtime, max €50k schade.",
    hint_en: "Define how much risk is acceptable: e.g. max 4 hours downtime, max €50k damage.",
    hint_fr: "Définissez le niveau de risque acceptable : p.ex. max 4h d'indisponibilité, max 50k€ de dommages." },
  { id: "ID.RM-3", category: "ID", subcategory: "RM", steps: [1],
    nl: "De organisatie bepaalt haar risicotolerantie op basis van haar rol in de kritieke infrastructuur.",
    en: "The organization determines its risk tolerance based on its role in critical infrastructure.",
    fr: "L'organisation détermine sa tolérance au risque en fonction de son rôle dans l'infrastructure critique.",
    hint_nl: "Hoe kritischer je diensten voor de samenleving, hoe lager je risicotolerantie moet zijn.",
    hint_en: "The more critical your services to society, the lower your risk tolerance should be.",
    hint_fr: "Plus vos services sont critiques pour la société, plus votre tolérance au risque doit être faible." },

  // Supply Chain
  { id: "ID.SC-2", category: "ID", subcategory: "SC", steps: [5],
    nl: "Leveranciers en externe partners worden geïdentificeerd, geprioriteerd en beoordeeld.",
    en: "Suppliers and third-party partners are identified, prioritized, and assessed using a cyber supply chain risk assessment.",
    fr: "Les fournisseurs et partenaires tiers sont identifiés, priorisés et évalués via une évaluation des risques.",
    hint_nl: "Maak een lijst van je leveranciers en beoordeel hun cybersecurity-volwassenheid.",
    hint_en: "List your suppliers and assess their cybersecurity maturity.",
    hint_fr: "Dressez la liste de vos fournisseurs et évaluez leur maturité en cybersécurité." },
  { id: "ID.SC-3", category: "ID", subcategory: "SC", steps: [5],
    nl: "Contracten met leveranciers bevatten passende cyberbeveiligingsmaatregelen.",
    en: "Contracts with suppliers include appropriate cybersecurity measures aligned with the organization's program.",
    fr: "Les contrats avec les fournisseurs incluent des mesures de cybersécurité appropriées.",
    hint_nl: "Neem beveiligingseisen, meldplicht en audit-rechten op in leverancierscontracten.",
    hint_en: "Include security requirements, notification obligations and audit rights in supplier contracts.",
    hint_fr: "Incluez des exigences de sécurité, obligations de notification et droits d'audit dans les contrats fournisseurs." },
  { id: "ID.SC-4", category: "ID", subcategory: "SC", steps: [5],
    nl: "Leveranciers worden routinematig beoordeeld via audits of evaluaties.",
    en: "Suppliers are routinely assessed through audits, test results, or evaluations to confirm contractual compliance.",
    fr: "Les fournisseurs sont régulièrement évalués par des audits ou évaluations pour confirmer le respect contractuel.",
    hint_nl: "Plan jaarlijks een check of leveranciers hun beveiligingsafspraken nakomen.",
    hint_en: "Schedule annual checks to verify suppliers comply with their security agreements.",
    hint_fr: "Planifiez des vérifications annuelles pour confirmer que les fournisseurs respectent leurs engagements de sécurité." },
  { id: "ID.SC-5", category: "ID", subcategory: "SC", steps: [5],
    nl: "Respons- en herstelplanning en tests worden uitgevoerd met leveranciers.",
    en: "Response and recovery planning and testing are conducted with suppliers and third parties.",
    fr: "La planification et les tests de réponse et de reprise sont menés avec les fournisseurs et tiers.",
    hint_nl: "Oefen samen met je IT-leverancier wat er gebeurt als hun systeem uitvalt of gehackt wordt.",
    hint_en: "Practice together with your IT supplier what happens if their system goes down or is hacked.",
    hint_fr: "Pratiquez avec votre fournisseur IT ce qui se passe si leur système tombe en panne ou est piraté." },

  // ===== BESCHERMEN (PR) =====
  // Access Control
  { id: "PR.AC-1", category: "PR", subcategory: "AC", steps: [2],
    nl: "Identiteiten en credentials worden afgegeven, beheerd, geverifieerd en gecontroleerd.",
    en: "Identities and credentials are issued, managed, verified, revoked, and audited for authorized devices and users.",
    fr: "Les identités et credentials sont émis, gérés, vérifiés, révoqués et audités.",
    hint_nl: "Beheer gebruikersaccounts en wachtwoorden centraal. Schakel vertrokken medewerkers direct uit.",
    hint_en: "Manage user accounts and passwords centrally. Disable departed employees immediately.",
    hint_fr: "Gérez les comptes utilisateurs et mots de passe de manière centralisée. Désactivez immédiatement les employés partis." },
  { id: "PR.AC-2", category: "PR", subcategory: "AC", steps: [2],
    nl: "De fysieke toegang tot activa wordt beheerd en beschermd.",
    en: "Physical access to assets is managed and protected.",
    fr: "L'accès physique aux actifs est géré et protégé.",
    hint_nl: "Gebruik sleutels, badges of codes voor toegang. Trek deze in bij vertrek van personeel. Zet een alarm op gebouw/serverruimte.",
    hint_en: "Use keys, badges or codes for access. Revoke them when staff leave. Set alarms on building/server room.",
    hint_fr: "Utilisez des clés, badges ou codes d'accès. Révoquez-les au départ du personnel. Installez une alarme sur le bâtiment/salle serveur." },
  { id: "PR.AC-3", category: "PR", subcategory: "AC", steps: [2],
    nl: "De toegang op afstand wordt beheerd.",
    en: "Remote access is managed.",
    fr: "L'accès à distance est géré.",
    hint_nl: "Gebruik VPN of beveiligde verbindingen voor thuiswerk. Schakel MFA in voor remote toegang.",
    hint_en: "Use VPN or secure connections for remote work. Enable MFA for remote access.",
    hint_fr: "Utilisez un VPN ou des connexions sécurisées pour le télétravail. Activez le MFA pour l'accès à distance." },
  { id: "PR.AC-4", category: "PR", subcategory: "AC", steps: [2],
    nl: "Toegangsrechten worden beheerd met least privilege en scheiding van taken.",
    en: "Access permissions are managed incorporating least privilege and separation of duties.",
    fr: "Les droits d'accès sont gérés selon le moindre privilège et la séparation des tâches.",
    hint_nl: "Geef medewerkers alleen de rechten die ze nodig hebben. Geen standaard admin-rechten voor iedereen.",
    hint_en: "Give employees only the permissions they need. No default admin rights for everyone.",
    hint_fr: "Donnez aux employés uniquement les droits dont ils ont besoin. Pas de droits admin par défaut pour tous." },
  { id: "PR.AC-5", category: "PR", subcategory: "AC", steps: [2],
    nl: "Netwerkintegriteit (netwerksegregatie, netwerksegmentatie) wordt beschermd.",
    en: "Network integrity is protected (e.g., network segregation, network segmentation).",
    fr: "L'intégrité du réseau est protégée (ségrégation réseau, segmentation réseau).",
    hint_nl: "Scheid je netwerk: gasten-wifi apart, servers apart van werkstations, IoT apart.",
    hint_en: "Separate your network: guest WiFi apart, servers apart from workstations, IoT apart.",
    hint_fr: "Séparez votre réseau : WiFi invités à part, serveurs séparés des postes de travail, IoT à part." },
  { id: "PR.AC-6", category: "PR", subcategory: "AC", steps: [2],
    nl: "Identiteiten worden aangetoond en verbonden aan credentials.",
    en: "Identities are proofed and bound to credentials and asserted in interactions.",
    fr: "Les identités sont vérifiées et liées aux credentials dans les interactions.",
    hint_nl: "Verifieer de identiteit van gebruikers voordat je accounts aanmaakt (bijv. ID-controle bij onboarding).",
    hint_en: "Verify user identity before creating accounts (e.g. ID check during onboarding).",
    hint_fr: "Vérifiez l'identité des utilisateurs avant de créer des comptes (p.ex. contrôle d'identité lors de l'intégration)." },
  { id: "PR.AC-7", category: "PR", subcategory: "AC", steps: [2],
    nl: "Gebruikers, apparaten en andere activa worden geverifieerd op basis van risico.",
    en: "Users, devices, and other assets are authenticated commensurate with risk.",
    fr: "Les utilisateurs, appareils et actifs sont authentifiés en fonction du risque.",
    hint_nl: "Gebruik MFA voor gevoelige systemen. Hogere risicotoegang = sterkere authenticatie.",
    hint_en: "Use MFA for sensitive systems. Higher risk access = stronger authentication.",
    hint_fr: "Utilisez le MFA pour les systèmes sensibles. Accès à risque élevé = authentification renforcée." },

  // Awareness & Training
  { id: "PR.AT-1", category: "PR", subcategory: "AT", steps: [4],
    nl: "Alle gebruikers worden geïnformeerd en opgeleid.",
    en: "All users are informed and trained.",
    fr: "Tous les utilisateurs sont informés et formés.",
    hint_nl: "Organiseer jaarlijks een security awareness training voor alle medewerkers (bijv. phishing herkennen).",
    hint_en: "Organize annual security awareness training for all employees (e.g. recognizing phishing).",
    hint_fr: "Organisez une formation annuelle de sensibilisation à la sécurité pour tous les employés (p.ex. reconnaître le phishing)." },
  { id: "PR.AT-2", category: "PR", subcategory: "AT", steps: [4],
    nl: "Geprivilegieerde gebruikers begrijpen hun rollen en verantwoordelijkheden.",
    en: "Privileged users understand their roles and responsibilities.",
    fr: "Les utilisateurs privilégiés comprennent leurs rôles et responsabilités.",
    hint_nl: "IT-admins krijgen extra training over veilig beheer van admin-accounts en rechten.",
    hint_en: "IT admins receive extra training on safe management of admin accounts and privileges.",
    hint_fr: "Les administrateurs IT reçoivent une formation supplémentaire sur la gestion sécurisée des comptes admin." },
  { id: "PR.AT-3", category: "PR", subcategory: "AT", steps: [4, 5],
    nl: "Belanghebbenden van derden begrijpen hun rol en verantwoordelijkheden.",
    en: "Third-party stakeholders understand their roles and responsibilities.",
    fr: "Les parties prenantes tierces comprennent leurs rôles et responsabilités.",
    hint_nl: "Informeer externe partners (leveranciers, consultants) over je beveiligingsregels.",
    hint_en: "Inform external partners (suppliers, consultants) about your security rules.",
    hint_fr: "Informez les partenaires externes (fournisseurs, consultants) de vos règles de sécurité." },
  { id: "PR.AT-4", category: "PR", subcategory: "AT", steps: [4],
    nl: "Hogere leidinggevenden begrijpen hun taken en verantwoordelijkheden.",
    en: "Senior executives understand their roles and responsibilities.",
    fr: "Les cadres supérieurs comprennent leurs rôles et responsabilités.",
    hint_nl: "Briefing de directie: zij zijn aansprakelijk onder NIS2 en moeten cyberrisico's begrijpen.",
    hint_en: "Brief the board: they are liable under NIS2 and must understand cyber risks.",
    hint_fr: "Briefez la direction : ils sont responsables sous NIS2 et doivent comprendre les cyber-risques." },
  { id: "PR.AT-5", category: "PR", subcategory: "AT", steps: [4],
    nl: "Fysiek en cyberbeveiligingspersoneel begrijpt hun rollen.",
    en: "Physical and cybersecurity personnel understand their roles and responsibilities.",
    fr: "Le personnel de sécurité physique et cybersécurité comprend ses rôles et responsabilités.",
    hint_nl: "Security officers en IT-team weten exact wat te doen bij een incident of inbraak.",
    hint_en: "Security officers and IT team know exactly what to do during an incident or breach.",
    hint_fr: "Les agents de sécurité et l'équipe IT savent exactement quoi faire lors d'un incident ou d'une violation." },

  // Data Security
  { id: "PR.DS-1", category: "PR", subcategory: "DS", steps: [2],
    nl: "Data in rust is beschermd.",
    en: "Data at rest is protected.",
    fr: "Les données au repos sont protégées.",
    hint_nl: "Versleutel harde schijven (BitLocker/FileVault) en databases met gevoelige gegevens.",
    hint_en: "Encrypt hard drives (BitLocker/FileVault) and databases containing sensitive data.",
    hint_fr: "Chiffrez les disques durs (BitLocker/FileVault) et les bases de données contenant des données sensibles." },
  { id: "PR.DS-2", category: "PR", subcategory: "DS", steps: [2],
    nl: "Data-in-transitie is beschermd.",
    en: "Data in transit is protected.",
    fr: "Les données en transit sont protégées.",
    hint_nl: "Gebruik HTTPS, TLS en versleutelde e-mail voor het versturen van gevoelige informatie.",
    hint_en: "Use HTTPS, TLS and encrypted email for sending sensitive information.",
    hint_fr: "Utilisez HTTPS, TLS et e-mail chiffré pour l'envoi d'informations sensibles." },
  { id: "PR.DS-3", category: "PR", subcategory: "DS", steps: [2],
    nl: "Activa worden formeel beheerd gedurende verhuizing, overdracht en verwijdering.",
    en: "Assets are formally managed throughout removal, transfers, and disposition.",
    fr: "Les actifs sont formellement gérés lors du retrait, transfert et mise au rebut.",
    hint_nl: "Wis data veilig van oude laptops/telefoons voordat je ze weggooit of doorgeeft.",
    hint_en: "Securely wipe data from old laptops/phones before disposing of or transferring them.",
    hint_fr: "Effacez les données des anciens laptops/téléphones de manière sécurisée avant de les jeter ou les transférer." },
  { id: "PR.DS-4", category: "PR", subcategory: "DS", steps: [2],
    nl: "Voldoende capaciteit om de beschikbaarheid te waarborgen.",
    en: "Adequate capacity to ensure availability is maintained.",
    fr: "Une capacité adéquate est maintenue pour assurer la disponibilité.",
    hint_nl: "Monitor schijfruimte, bandbreedte en serverbelasting. Voorkom dat systemen vollopen.",
    hint_en: "Monitor disk space, bandwidth and server load. Prevent systems from running out of capacity.",
    hint_fr: "Surveillez l'espace disque, la bande passante et la charge serveur. Évitez la saturation des systèmes." },
  { id: "PR.DS-5", category: "PR", subcategory: "DS", steps: [2],
    nl: "Beveiligingen tegen datalekken worden geïmplementeerd.",
    en: "Protections against data leaks are implemented.",
    fr: "Des protections contre les fuites de données sont mises en œuvre.",
    hint_nl: "Beperk wie bestanden kan delen/kopiëren. Gebruik DLP-tools of restrict USB-gebruik.",
    hint_en: "Restrict who can share/copy files. Use DLP tools or restrict USB usage.",
    hint_fr: "Limitez qui peut partager/copier des fichiers. Utilisez des outils DLP ou restreignez l'usage USB." },
  { id: "PR.DS-6", category: "PR", subcategory: "DS", steps: [2],
    nl: "Integriteitscontrolemechanismen worden gebruikt om software en informatie te controleren.",
    en: "Integrity checking mechanisms are used to verify software, firmware, and information integrity.",
    fr: "Des mécanismes de contrôle d'intégrité sont utilisés pour vérifier l'intégrité des logiciels et informations.",
    hint_nl: "Gebruik checksums of digitale handtekeningen om te controleren dat software niet gewijzigd is.",
    hint_en: "Use checksums or digital signatures to verify software has not been tampered with.",
    hint_fr: "Utilisez des sommes de contrôle ou signatures numériques pour vérifier que les logiciels n'ont pas été altérés." },
  { id: "PR.DS-7", category: "PR", subcategory: "DS", steps: [2],
    nl: "De ontwikkelings- en testomgevingen zijn gescheiden van de productieomgeving.",
    en: "Development and testing environments are separate from the production environment.",
    fr: "Les environnements de développement et de test sont séparés de l'environnement de production.",
    hint_nl: "Test nooit met productiedata. Houd ontwikkel-, test- en live-omgevingen strikt gescheiden.",
    hint_en: "Never test with production data. Keep development, test and live environments strictly separate.",
    hint_fr: "Ne testez jamais avec des données de production. Gardez les environnements dev, test et live strictement séparés." },

  // Information Protection Processes
  { id: "PR.IP-1", category: "PR", subcategory: "IP", steps: [2],
    nl: "Basisconfiguratie van IT-systemen wordt gecreëerd en onderhouden met beveiligingsbeginselen.",
    en: "A baseline configuration of IT systems is created and maintained incorporating security principles.",
    fr: "Une configuration de base des systèmes IT est créée et maintenue intégrant les principes de sécurité.",
    hint_nl: "Documenteer een standaard veilige configuratie voor laptops, servers en netwerkapparaten.",
    hint_en: "Document a standard secure configuration for laptops, servers and network devices.",
    hint_fr: "Documentez une configuration sécurisée standard pour les laptops, serveurs et équipements réseau." },
  { id: "PR.IP-2", category: "PR", subcategory: "IP", steps: [2],
    nl: "Een levenscyclus voor systeemontwikkeling wordt geïmplementeerd.",
    en: "A System Development Life Cycle to manage systems is implemented.",
    fr: "Un cycle de vie de développement système est mis en œuvre pour gérer les systèmes.",
    hint_nl: "Volg een vaste aanpak voor ontwikkeling: ontwerp → bouw → test → deploy → onderhoud.",
    hint_en: "Follow a structured development approach: design → build → test → deploy → maintain.",
    hint_fr: "Suivez une approche structurée de développement : conception → construction → test → déploiement → maintenance." },
  { id: "PR.IP-3", category: "PR", subcategory: "IP", steps: [2],
    nl: "Er zijn processen voor het beheer van configuratiewijzigingen aanwezig.",
    en: "Configuration change control processes are in place.",
    fr: "Des processus de contrôle des modifications de configuration sont en place.",
    hint_nl: "Elke wijziging aan systemen wordt aangevraagd, goedgekeurd, getest en gedocumenteerd.",
    hint_en: "Every change to systems is requested, approved, tested and documented.",
    hint_fr: "Chaque modification des systèmes est demandée, approuvée, testée et documentée." },
  { id: "PR.IP-4", category: "PR", subcategory: "IP", steps: [2],
    nl: "Er worden back-ups van informatie gemaakt, onderhouden en getest.",
    en: "Backups of information are conducted, maintained, and tested.",
    fr: "Des sauvegardes d'information sont effectuées, maintenues et testées.",
    hint_nl: "Maak dagelijks backups, bewaar ze offsite en test maandelijks of je ze kunt terugzetten.",
    hint_en: "Make daily backups, store them offsite and test monthly if you can restore them.",
    hint_fr: "Faites des sauvegardes quotidiennes, stockez-les hors site et testez mensuellement si vous pouvez les restaurer." },
  { id: "PR.IP-5", category: "PR", subcategory: "IP", steps: [2],
    nl: "Beleid m.b.t. de fysieke bedrijfsomgeving voor bedrijfsmiddelen wordt nageleefd.",
    en: "Policy regarding the physical operating environment for organizational assets is met.",
    fr: "La politique relative à l'environnement physique d'exploitation des actifs est respectée.",
    hint_nl: "Zorg voor klimaatbeheersing, brandbeveiliging en stroomvoorziening in de serverruimte.",
    hint_en: "Ensure climate control, fire protection and power supply in the server room.",
    hint_fr: "Assurez la climatisation, la protection incendie et l'alimentation électrique de la salle serveur." },
  { id: "PR.IP-6", category: "PR", subcategory: "IP", steps: [2],
    nl: "Gegevens worden vernietigd overeenkomstig beleid.",
    en: "Data is destroyed according to policy.",
    fr: "Les données sont détruites conformément à la politique.",
    hint_nl: "Vernietig vertrouwelijke documenten met een shredder. Wis digitale data onherstelbaar.",
    hint_en: "Destroy confidential documents with a shredder. Wipe digital data irreversibly.",
    hint_fr: "Détruisez les documents confidentiels avec un destructeur. Effacez les données numériques de manière irréversible." },
  { id: "PR.IP-7", category: "PR", subcategory: "IP", steps: [6],
    nl: "De beschermingsprocessen worden verbeterd.",
    en: "Protection processes are improved.",
    fr: "Les processus de protection sont améliorés.",
    hint_nl: "Evalueer je beveiligingsmaatregelen jaarlijks en verbeter op basis van incidenten en audits.",
    hint_en: "Evaluate your security measures annually and improve based on incidents and audits.",
    hint_fr: "Évaluez vos mesures de sécurité annuellement et améliorez-les en fonction des incidents et audits." },
  { id: "PR.IP-8", category: "PR", subcategory: "IP", steps: [6],
    nl: "De doeltreffendheid van beschermingstechnologieën wordt gedeeld.",
    en: "Effectiveness of protection technologies is shared.",
    fr: "L'efficacité des technologies de protection est partagée.",
    hint_nl: "Deel ervaringen over welke beveiligingstools werken met sectorgenoten of via het CCB.",
    hint_en: "Share experiences about which security tools work with sector peers or via CCB.",
    hint_fr: "Partagez les expériences sur les outils de sécurité efficaces avec les pairs du secteur ou via le CCB." },
  { id: "PR.IP-9", category: "PR", subcategory: "IP", steps: [3],
    nl: "Responsplannen en herstelplannen zijn aanwezig en worden beheerd.",
    en: "Response plans (Incident Response and Business Continuity) and recovery plans are in place and managed.",
    fr: "Les plans de réponse et de reprise sont en place et gérés.",
    hint_nl: "Stel een incident response plan en een business continuity plan op en hou ze actueel.",
    hint_en: "Create an incident response plan and a business continuity plan and keep them up to date.",
    hint_fr: "Établissez un plan de réponse aux incidents et un plan de continuité d'activité et maintenez-les à jour." },
  { id: "PR.IP-11", category: "PR", subcategory: "IP", steps: [4],
    nl: "Cyberbeveiliging is opgenomen in het personeelsbeheer.",
    en: "Cybersecurity is included in human resources practices.",
    fr: "La cybersécurité est intégrée dans les pratiques de ressources humaines.",
    hint_nl: "Neem security op in onboarding, functiebeschrijvingen en exit-procedures.",
    hint_en: "Include security in onboarding, job descriptions and exit procedures.",
    hint_fr: "Intégrez la sécurité dans l'intégration, les descriptions de poste et les procédures de départ." },
  { id: "PR.IP-12", category: "PR", subcategory: "IP", steps: [6],
    nl: "Een plan voor het beheer van kwetsbaarheden wordt ontwikkeld en uitgevoerd.",
    en: "A vulnerability management plan is developed and implemented.",
    fr: "Un plan de gestion des vulnérabilités est développé et mis en œuvre.",
    hint_nl: "Scan maandelijks op kwetsbaarheden en patch kritieke lekken binnen 48 uur.",
    hint_en: "Scan monthly for vulnerabilities and patch critical ones within 48 hours.",
    hint_fr: "Analysez mensuellement les vulnérabilités et corrigez les critiques dans les 48 heures." },

  // Maintenance
  { id: "PR.MA-1", category: "PR", subcategory: "MA", steps: [2],
    nl: "Onderhoud en reparatie worden uitgevoerd en geregistreerd met goedgekeurde gereedschappen.",
    en: "Maintenance and repair are performed and logged with approved and controlled tools.",
    fr: "La maintenance et les réparations sont effectuées et enregistrées avec des outils approuvés et contrôlés.",
    hint_nl: "Log elk onderhoud aan servers en netwerk. Gebruik alleen goedgekeurde tools en firmware.",
    hint_en: "Log all maintenance on servers and network. Use only approved tools and firmware.",
    hint_fr: "Enregistrez toute maintenance sur les serveurs et le réseau. Utilisez uniquement des outils et firmware approuvés." },
  { id: "PR.MA-2", category: "PR", subcategory: "MA", steps: [2],
    nl: "Onderhoud op afstand wordt goedgekeurd, geregistreerd en voorkomt ongeoorloofde toegang.",
    en: "Remote maintenance is approved, logged, and performed in a manner that prevents unauthorized access.",
    fr: "La maintenance à distance est approuvée, enregistrée et réalisée de manière à prévenir l'accès non autorisé.",
    hint_nl: "Geef leveranciers alleen tijdelijke remote-toegang en monitor hun sessies.",
    hint_en: "Give suppliers only temporary remote access and monitor their sessions.",
    hint_fr: "Donnez aux fournisseurs uniquement un accès distant temporaire et surveillez leurs sessions." },

  // Protective Technology
  { id: "PR.PT-1", category: "PR", subcategory: "PT", steps: [6],
    nl: "Registraties van audits/logs worden vastgesteld en herzien overeenkomstig beleid.",
    en: "Audit/log records are determined, documented, implemented, and reviewed in accordance with policy.",
    fr: "Les registres d'audit/journaux sont déterminés, documentés, mis en œuvre et révisés conformément à la politique.",
    hint_nl: "Bewaar logbestanden van alle systemen minstens 6 maanden. Controleer ze regelmatig op afwijkingen.",
    hint_en: "Keep log files from all systems for at least 6 months. Regularly check them for anomalies.",
    hint_fr: "Conservez les fichiers journaux de tous les systèmes pendant au moins 6 mois. Vérifiez-les régulièrement." },
  { id: "PR.PT-2", category: "PR", subcategory: "PT", steps: [2],
    nl: "Verwisselbare media worden beschermd en het gebruik ervan wordt beperkt.",
    en: "Removable media is protected and its use restricted according to policy.",
    fr: "Les supports amovibles sont protégés et leur utilisation est restreinte conformément à la politique.",
    hint_nl: "Beperk USB-sticks en externe schijven. Scan ze altijd op malware voor gebruik.",
    hint_en: "Restrict USB drives and external disks. Always scan them for malware before use.",
    hint_fr: "Restreignez les clés USB et disques externes. Analysez-les toujours pour les malwares avant utilisation." },
  { id: "PR.PT-3", category: "PR", subcategory: "PT", steps: [2],
    nl: "Het beginsel van minimale functionaliteit wordt toegepast.",
    en: "The principle of least functionality is incorporated by configuring systems to provide only essential capabilities.",
    fr: "Le principe de fonctionnalité minimale est appliqué en configurant les systèmes pour ne fournir que les capacités essentielles.",
    hint_nl: "Schakel onnodige diensten, poorten en software uit op servers en werkstations.",
    hint_en: "Disable unnecessary services, ports and software on servers and workstations.",
    hint_fr: "Désactivez les services, ports et logiciels inutiles sur les serveurs et postes de travail." },
  { id: "PR.PT-4", category: "PR", subcategory: "PT", steps: [2],
    nl: "Communicatie- en besturingsnetwerken zijn beveiligd.",
    en: "Communications and control networks are protected.",
    fr: "Les réseaux de communication et de contrôle sont protégés.",
    hint_nl: "Installeer firewalls, IDS/IPS en monitor je netwerkverkeer op verdachte activiteit.",
    hint_en: "Install firewalls, IDS/IPS and monitor your network traffic for suspicious activity.",
    hint_fr: "Installez des pare-feu, IDS/IPS et surveillez votre trafic réseau pour détecter les activités suspectes." },

  // ===== DETECTEREN (DE) =====
  // Anomalies & Events
  { id: "DE.AE-2", category: "DE", subcategory: "AE", steps: [6],
    nl: "Gedetecteerde events worden geanalyseerd om aanvalsdoelen en -methoden te begrijpen.",
    en: "Detected events are analyzed to understand attack targets and methods.",
    fr: "Les événements détectés sont analysés pour comprendre les cibles et méthodes d'attaque.",
    hint_nl: "Analyseer beveiligingsmeldingen: wat werd aangevallen, hoe, en wat was het doel?",
    hint_en: "Analyze security alerts: what was attacked, how, and what was the target?",
    hint_fr: "Analysez les alertes de sécurité : qu'est-ce qui a été attaqué, comment et quel était l'objectif ?" },
  { id: "DE.AE-3", category: "DE", subcategory: "AE", steps: [6],
    nl: "Gegevens m.b.t. events worden verzameld en gecorreleerd uit meerdere bronnen.",
    en: "Event data are collected and correlated from multiple sources and sensors.",
    fr: "Les données d'événements sont collectées et corrélées à partir de multiples sources et capteurs.",
    hint_nl: "Verzamel logs van firewall, servers, endpoints en correleer ze om patronen te ontdekken.",
    hint_en: "Collect logs from firewall, servers, endpoints and correlate them to discover patterns.",
    hint_fr: "Collectez les journaux du pare-feu, serveurs, endpoints et corrèlez-les pour découvrir des tendances." },
  { id: "DE.AE-5", category: "DE", subcategory: "AE", steps: [6],
    nl: "Er worden alarmdrempels voor incidenten vastgesteld.",
    en: "Incident alert thresholds are established.",
    fr: "Des seuils d'alerte d'incidents sont établis.",
    hint_nl: "Definieer wanneer een melding een incident wordt: bijv. 5 mislukte logins = alarm.",
    hint_en: "Define when an alert becomes an incident: e.g. 5 failed logins = alarm.",
    hint_fr: "Définissez quand une alerte devient un incident : p.ex. 5 connexions échouées = alarme." },

  // Continuous Monitoring
  { id: "DE.CM-1", category: "DE", subcategory: "CM", steps: [6],
    nl: "Het netwerk wordt bewaakt om potentiële cyberbeveiligingsevents op te sporen.",
    en: "The network is monitored to detect potential cybersecurity events.",
    fr: "Le réseau est surveillé pour détecter les événements potentiels de cybersécurité.",
    hint_nl: "Gebruik een SIEM of monitoring-tool om je netwerk 24/7 te bewaken op verdacht verkeer.",
    hint_en: "Use a SIEM or monitoring tool to watch your network 24/7 for suspicious traffic.",
    hint_fr: "Utilisez un SIEM ou outil de surveillance pour surveiller votre réseau 24h/24 contre le trafic suspect." },
  { id: "DE.CM-2", category: "DE", subcategory: "CM", steps: [6],
    nl: "De fysieke omgeving wordt bewaakt om potentiële cyberbeveiligingsgebeurtenissen op te sporen.",
    en: "The physical environment is monitored to detect potential cybersecurity events.",
    fr: "L'environnement physique est surveillé pour détecter les événements potentiels de cybersécurité.",
    hint_nl: "Camera's, deur-sensoren en toegangslogboeken in de serverruimte en datacenters.",
    hint_en: "Cameras, door sensors and access logs in the server room and data centers.",
    hint_fr: "Caméras, capteurs de porte et journaux d'accès dans la salle serveur et les centres de données." },
  { id: "DE.CM-3", category: "DE", subcategory: "CM", steps: [6],
    nl: "Personeelsactiviteiten worden gemonitord om potentiële cyberbeveiligingsgebeurtenissen op te sporen.",
    en: "Personnel activity is monitored to detect potential cybersecurity events.",
    fr: "L'activité du personnel est surveillée pour détecter les événements potentiels de cybersécurité.",
    hint_nl: "Monitor ongewoon gedrag: inloggen buiten werkuren, grote datadownloads, ongebruikelijke toegang.",
    hint_en: "Monitor unusual behavior: logins outside work hours, large data downloads, unusual access.",
    hint_fr: "Surveillez les comportements inhabituels : connexions hors heures, téléchargements massifs, accès inhabituels." },
  { id: "DE.CM-4", category: "DE", subcategory: "CM", steps: [6],
    nl: "Kwaadaardige code wordt gedetecteerd.",
    en: "Malicious code is detected.",
    fr: "Le code malveillant est détecté.",
    hint_nl: "Installeer antivirus/EDR op alle endpoints en houd virusdefinities actueel.",
    hint_en: "Install antivirus/EDR on all endpoints and keep virus definitions up to date.",
    hint_fr: "Installez un antivirus/EDR sur tous les endpoints et maintenez les définitions de virus à jour." },
  { id: "DE.CM-5", category: "DE", subcategory: "CM", steps: [6],
    nl: "Ongeoorloofde mobiele code wordt gedetecteerd.",
    en: "Unauthorized mobile code is detected.",
    fr: "Le code mobile non autorisé est détecté.",
    hint_nl: "Blokkeer onbekende scripts en macro's. Sta alleen goedgekeurde mobiele code toe.",
    hint_en: "Block unknown scripts and macros. Only allow approved mobile code.",
    hint_fr: "Bloquez les scripts et macros inconnus. Autorisez uniquement le code mobile approuvé." },
  { id: "DE.CM-6", category: "DE", subcategory: "CM", steps: [5, 6],
    nl: "De activiteit van externe dienstverleners wordt gemonitord.",
    en: "External service provider activity is monitored to detect potential cybersecurity events.",
    fr: "L'activité des prestataires de services externes est surveillée pour détecter les événements de cybersécurité.",
    hint_nl: "Monitor wat externe IT-partners doen op je systemen. Log hun toegang en acties.",
    hint_en: "Monitor what external IT partners do on your systems. Log their access and actions.",
    hint_fr: "Surveillez ce que les partenaires IT externes font sur vos systèmes. Enregistrez leurs accès et actions." },
  { id: "DE.CM-7", category: "DE", subcategory: "CM", steps: [6],
    nl: "Monitoring op onbevoegd personeel, verbindingen, apparatuur en software.",
    en: "Monitoring for unauthorized personnel, connections, devices, and software is performed.",
    fr: "La surveillance du personnel, connexions, appareils et logiciels non autorisés est effectuée.",
    hint_nl: "Detecteer onbekende apparaten op je netwerk (rogue devices) en ongeautoriseerde software.",
    hint_en: "Detect unknown devices on your network (rogue devices) and unauthorized software.",
    hint_fr: "Détectez les appareils inconnus sur votre réseau (appareils non autorisés) et les logiciels non autorisés." },
  { id: "DE.CM-8", category: "DE", subcategory: "CM", steps: [6],
    nl: "Kwetsbaarheidsscans worden uitgevoerd.",
    en: "Vulnerability scans are performed.",
    fr: "Des analyses de vulnérabilités sont effectuées.",
    hint_nl: "Scan je systemen minstens maandelijks met tools als Nessus, OpenVAS of Qualys.",
    hint_en: "Scan your systems at least monthly with tools like Nessus, OpenVAS or Qualys.",
    hint_fr: "Analysez vos systèmes au moins mensuellement avec des outils comme Nessus, OpenVAS ou Qualys." },

  // Detection Processes
  { id: "DE.DP-2", category: "DE", subcategory: "DP", steps: [6],
    nl: "Detectie moet gebeuren conform alle toepasselijke eisen.",
    en: "Detection activities comply with all applicable requirements.",
    fr: "Les activités de détection sont conformes à toutes les exigences applicables.",
    hint_nl: "Zorg dat je monitoring voldoet aan privacy- en arbeidswetgeving (bijv. GDPR).",
    hint_en: "Ensure your monitoring complies with privacy and labor legislation (e.g. GDPR).",
    hint_fr: "Assurez-vous que votre surveillance est conforme à la législation sur la vie privée et le travail (p.ex. RGPD)." },
  { id: "DE.DP-3", category: "DE", subcategory: "DP", steps: [6],
    nl: "Detectieprocessen worden getest.",
    en: "Detection processes are tested.",
    fr: "Les processus de détection sont testés.",
    hint_nl: "Test regelmatig of je alarmen werken: simuleer een aanval en kijk of het gedetecteerd wordt.",
    hint_en: "Regularly test if your alarms work: simulate an attack and check if it's detected.",
    hint_fr: "Testez régulièrement si vos alarmes fonctionnent : simulez une attaque et vérifiez si elle est détectée." },
  { id: "DE.DP-4", category: "DE", subcategory: "DP", steps: [3, 6],
    nl: "Informatie over gedetecteerde events wordt gecommuniceerd.",
    en: "Event detection information is communicated.",
    fr: "Les informations sur les événements détectés sont communiquées.",
    hint_nl: "Meld beveiligingsincidenten direct aan het juiste team en documenteer ze.",
    hint_en: "Report security incidents immediately to the right team and document them.",
    hint_fr: "Signalez immédiatement les incidents de sécurité à l'équipe appropriée et documentez-les." },
  { id: "DE.DP-5", category: "DE", subcategory: "DP", steps: [6],
    nl: "De processen voor het detecteren van abnormale events worden voortdurend verbeterd.",
    en: "Detection processes are continuously improved.",
    fr: "Les processus de détection sont continuellement améliorés.",
    hint_nl: "Leer van elk incident: pas je detectieregels en alarmen aan op basis van nieuwe dreigingen.",
    hint_en: "Learn from every incident: adjust your detection rules and alarms based on new threats.",
    hint_fr: "Apprenez de chaque incident : ajustez vos règles de détection et alarmes en fonction des nouvelles menaces." },

  // ===== REAGEREN (RS) =====
  // Response Planning
  { id: "RS.RP-1", category: "RS", subcategory: "RP", steps: [3],
    nl: "Het responsplan wordt uitgevoerd tijdens of na een incident.",
    en: "Response plan is executed during or after an incident.",
    fr: "Le plan de réponse est exécuté pendant ou après un incident.",
    hint_nl: "Activeer je incident response plan zodra een cyberincident bevestigd is.",
    hint_en: "Activate your incident response plan as soon as a cyber incident is confirmed.",
    hint_fr: "Activez votre plan de réponse aux incidents dès qu'un cyber-incident est confirmé." },

  // Communications
  { id: "RS.CO-1", category: "RS", subcategory: "CO", steps: [3],
    nl: "Het personeel kent zijn rol en volgorde van handelen wanneer een reactie nodig is.",
    en: "Personnel know their role and order of operations when a response is needed.",
    fr: "Le personnel connaît son rôle et l'ordre des opérations lorsqu'une réponse est nécessaire.",
    hint_nl: "Iedereen weet wie te bellen, wat te doen en in welke volgorde bij een incident.",
    hint_en: "Everyone knows who to call, what to do and in what order during an incident.",
    hint_fr: "Chacun sait qui appeler, quoi faire et dans quel ordre lors d'un incident." },
  { id: "RS.CO-2", category: "RS", subcategory: "CO", steps: [3],
    nl: "Incidenten worden gemeld overeenkomstig de vastgestelde criteria.",
    en: "Incidents are reported consistent with established criteria.",
    fr: "Les incidents sont signalés conformément aux critères établis.",
    hint_nl: "Meld incidenten binnen 24u aan het CCB/CSIRT indien vereist onder NIS2.",
    hint_en: "Report incidents within 24h to the CCB/CSIRT if required under NIS2.",
    hint_fr: "Signalez les incidents dans les 24h au CCB/CSIRT si requis sous NIS2." },
  { id: "RS.CO-3", category: "RS", subcategory: "CO", steps: [3],
    nl: "Informatie wordt gedeeld in overeenstemming met de responsplannen.",
    en: "Information is shared consistent with response plans.",
    fr: "L'information est partagée conformément aux plans de réponse.",
    hint_nl: "Deel relevante informatie met betrokken teams zonder vertrouwelijke data te lekken.",
    hint_en: "Share relevant information with involved teams without leaking confidential data.",
    hint_fr: "Partagez les informations pertinentes avec les équipes impliquées sans divulguer de données confidentielles." },
  { id: "RS.CO-4", category: "RS", subcategory: "CO", steps: [3],
    nl: "Coördinatie met belanghebbenden vindt plaats conform de responsplannen.",
    en: "Coordination with stakeholders occurs consistent with response plans.",
    fr: "La coordination avec les parties prenantes a lieu conformément aux plans de réponse.",
    hint_nl: "Coördineer met management, juridische dienst, verzekering en eventueel politie bij een ernstig incident.",
    hint_en: "Coordinate with management, legal, insurance and potentially law enforcement for serious incidents.",
    hint_fr: "Coordonnez avec la direction, le service juridique, l'assurance et éventuellement la police pour les incidents graves." },
  { id: "RS.CO-5", category: "RS", subcategory: "CO", steps: [3],
    nl: "Vrijwillige informatie-uitwisseling met externe belanghebbenden voor breder situationeel bewustzijn.",
    en: "Voluntary information sharing occurs with external stakeholders to achieve broader cybersecurity situational awareness.",
    fr: "Le partage volontaire d'informations avec les parties prenantes externes pour une meilleure conscience situationnelle.",
    hint_nl: "Deel dreigingsinformatie met sectorgenoten of via ISAC's om elkaar te versterken.",
    hint_en: "Share threat intelligence with sector peers or via ISACs to strengthen each other.",
    hint_fr: "Partagez les renseignements sur les menaces avec les pairs du secteur ou via les ISAC pour se renforcer mutuellement." },

  // Analysis
  { id: "RS.AN-1", category: "RS", subcategory: "AN", steps: [3],
    nl: "Meldingen van detectiesystemen worden onderzocht.",
    en: "Notifications from detection systems are investigated.",
    fr: "Les notifications des systèmes de détection sont examinées.",
    hint_nl: "Onderzoek elke security-alert: is het een vals alarm of een echt incident?",
    hint_en: "Investigate every security alert: is it a false alarm or a real incident?",
    hint_fr: "Examinez chaque alerte de sécurité : est-ce une fausse alerte ou un véritable incident ?" },
  { id: "RS.AN-2", category: "RS", subcategory: "AN", steps: [3],
    nl: "De gevolgen van het incident worden begrepen.",
    en: "The impact of the incident is understood.",
    fr: "L'impact de l'incident est compris.",
    hint_nl: "Bepaal de schade: welke data is getroffen, hoeveel systemen, welke klanten?",
    hint_en: "Determine the damage: which data is affected, how many systems, which customers?",
    hint_fr: "Déterminez les dommages : quelles données sont touchées, combien de systèmes, quels clients ?" },
  { id: "RS.AN-4", category: "RS", subcategory: "AN", steps: [3],
    nl: "Incidenten worden in categorieën ingedeeld overeenkomstig de responsplannen.",
    en: "Incidents are categorized consistent with response plans.",
    fr: "Les incidents sont catégorisés conformément aux plans de réponse.",
    hint_nl: "Classificeer incidenten: laag/midden/hoog/kritiek op basis van impact en urgentie.",
    hint_en: "Classify incidents: low/medium/high/critical based on impact and urgency.",
    hint_fr: "Classifiez les incidents : faible/moyen/élevé/critique en fonction de l'impact et de l'urgence." },
  { id: "RS.AN-5", category: "RS", subcategory: "AN", steps: [3],
    nl: "Processen voor het ontvangen, analyseren en reageren op kwetsbaarheden zijn vastgesteld.",
    en: "Processes are established for receiving, analyzing, and responding to disclosed vulnerabilities.",
    fr: "Des processus sont établis pour recevoir, analyser et répondre aux vulnérabilités divulguées.",
    hint_nl: "Heb een proces klaar wanneer iemand een kwetsbaarheid in je systemen meldt (responsible disclosure).",
    hint_en: "Have a process ready when someone reports a vulnerability in your systems (responsible disclosure).",
    hint_fr: "Ayez un processus prêt lorsque quelqu'un signale une vulnérabilité dans vos systèmes (divulgation responsable)." },

  // Mitigation
  { id: "RS.MI-1", category: "RS", subcategory: "MI", steps: [3],
    nl: "Incidenten worden beheerst.",
    en: "Incidents are contained.",
    fr: "Les incidents sont contenus.",
    hint_nl: "Isoleer getroffen systemen onmiddellijk om verdere verspreiding te voorkomen.",
    hint_en: "Isolate affected systems immediately to prevent further spread.",
    hint_fr: "Isolez immédiatement les systèmes touchés pour empêcher la propagation." },

  // Improvements
  { id: "RS.IM-1", category: "RS", subcategory: "IM", steps: [3, 6],
    nl: "In de responsplannen zijn de geleerde lessen verwerkt.",
    en: "Response plans incorporate lessons learned.",
    fr: "Les plans de réponse intègrent les leçons apprises.",
    hint_nl: "Na elk incident: evalueer wat goed ging en wat beter kan. Pas je plannen aan.",
    hint_en: "After each incident: evaluate what went well and what can improve. Update your plans.",
    hint_fr: "Après chaque incident : évaluez ce qui a bien fonctionné et ce qui peut être amélioré. Mettez à jour vos plans." },
  { id: "RS.IM-2", category: "RS", subcategory: "IM", steps: [3, 6],
    nl: "Reactie- en herstelstrategieën worden bijgewerkt.",
    en: "Response and recovery strategies are updated.",
    fr: "Les stratégies de réponse et de reprise sont mises à jour.",
    hint_nl: "Werk je incident- en herstelplannen bij op basis van nieuwe dreigingen en geleerde lessen.",
    hint_en: "Update your incident and recovery plans based on new threats and lessons learned.",
    hint_fr: "Mettez à jour vos plans d'incident et de reprise en fonction des nouvelles menaces et leçons apprises." },

  // ===== HERSTELLEN (RC) =====
  // Recovery Planning
  { id: "RC.RP-1", category: "RC", subcategory: "RP", steps: [3],
    nl: "Het herstelplan wordt uitgevoerd tijdens of na een cyberbeveiligingsincident.",
    en: "Recovery plan is executed during or after a cybersecurity incident.",
    fr: "Le plan de reprise est exécuté pendant ou après un incident de cybersécurité.",
    hint_nl: "Zet systemen terug op vanuit backups en volg je disaster recovery procedure stap voor stap.",
    hint_en: "Restore systems from backups and follow your disaster recovery procedure step by step.",
    hint_fr: "Restaurez les systèmes à partir des sauvegardes et suivez votre procédure de reprise étape par étape." },

  // Improvements
  { id: "RC.IM-1", category: "RC", subcategory: "IM", steps: [6],
    nl: "In de herstelplannen zijn de geleerde lessen verwerkt.",
    en: "Recovery plans incorporate lessons learned.",
    fr: "Les plans de reprise intègrent les leçons apprises.",
    hint_nl: "Verbeter je herstelplan na elk incident: was de backup bruikbaar? Was de RTO gehaald?",
    hint_en: "Improve your recovery plan after each incident: was the backup usable? Was the RTO met?",
    hint_fr: "Améliorez votre plan de reprise après chaque incident : la sauvegarde était-elle utilisable ? Le RTO a-t-il été atteint ?" },

  // Communications
  { id: "RC.CO-1", category: "RC", subcategory: "CO", steps: [3],
    nl: "De public relations worden beheerd.",
    en: "Public relations are managed.",
    fr: "Les relations publiques sont gérées.",
    hint_nl: "Bereid een communicatieplan voor: wie informeert klanten, pers en toezichthouders na een incident?",
    hint_en: "Prepare a communication plan: who informs customers, press and regulators after an incident?",
    hint_fr: "Préparez un plan de communication : qui informe les clients, la presse et les régulateurs après un incident ?" },
  { id: "RC.CO-3", category: "RC", subcategory: "CO", steps: [3],
    nl: "Herstelactiviteiten worden gecommuniceerd aan interne en externe belanghebbenden.",
    en: "Recovery activities are communicated to internal and external stakeholders and executive management teams.",
    fr: "Les activités de reprise sont communiquées aux parties prenantes internes et externes et aux équipes de direction.",
    hint_nl: "Houd alle betrokkenen op de hoogte van de voortgang: management, klanten, partners.",
    hint_en: "Keep all stakeholders informed of progress: management, customers, partners.",
    hint_fr: "Tenez toutes les parties prenantes informées de la progression : direction, clients, partenaires." },
];

export function getControlsByStep(stepIndex: number): CyFunControl[] {
  return CYFUN_CONTROLS.filter(c => c.steps.includes(stepIndex));
}

export function getControlsByCategory(category: string): CyFunControl[] {
  return CYFUN_CONTROLS.filter(c => c.category === category);
}

export function getControlText(control: CyFunControl, lang: Language): string {
  return control[lang];
}

export function getControlHint(control: CyFunControl, lang: Language): string {
  const key = `hint_${lang}` as keyof CyFunControl;
  return control[key] as string;
}

export function getControlExample(control: CyFunControl, lang: Language): string | undefined {
  const key = `example_${lang}` as keyof CyFunControl;
  return control[key] as string | undefined;
}

export function getCategoryName(category: string, lang: Language): string {
  return CYFUN_CATEGORIES[category]?.[lang] ?? category;
}
