import type { Language } from "./i18n";

export interface CyFunControl {
  id: string;
  category: "ID" | "PR" | "DE" | "RS" | "RC";
  subcategory: string;
  nl: string;
  en: string;
  fr: string;
  /** Roadmap step indices (0-based) this control maps to */
  steps: number[];
}

export const CYFUN_CATEGORIES: Record<string, { nl: string; en: string; fr: string; color: string }> = {
  ID: { nl: "Identificeren", en: "Identify", fr: "Identifier", color: "bg-blue-600" },
  PR: { nl: "Beschermen", en: "Protect", fr: "Protéger", color: "bg-green-600" },
  DE: { nl: "Detecteren", en: "Detect", fr: "Détecter", color: "bg-yellow-600" },
  RS: { nl: "Reageren", en: "Respond", fr: "Répondre", color: "bg-orange-600" },
  RC: { nl: "Herstellen", en: "Recover", fr: "Récupérer", color: "bg-red-600" },
};

export const CYFUN_CONTROLS: CyFunControl[] = [
  // ===== IDENTIFICEREN (ID) =====
  // Asset Management
  { id: "ID.AM-1", category: "ID", subcategory: "AM", steps: [0],
    nl: "Inventarisatie van de binnen de organisatie gebruikte fysieke apparaten en systemen.",
    en: "Inventory of physical devices and systems used within the organization.",
    fr: "Inventaire des appareils physiques et systèmes utilisés au sein de l'organisation." },
  { id: "ID.AM-2", category: "ID", subcategory: "AM", steps: [0],
    nl: "Inventarisatie van de binnen de organisatie gebruikte softwareplatforms en -toepassingen.",
    en: "Inventory of software platforms and applications used within the organization.",
    fr: "Inventaire des plateformes logicielles et applications utilisées au sein de l'organisation." },
  { id: "ID.AM-3", category: "ID", subcategory: "AM", steps: [0],
    nl: "De organisatorische communicatie- en gegevensstromen worden in kaart gebracht.",
    en: "Organizational communication and data flows are mapped.",
    fr: "Les flux de communication et de données organisationnels sont cartographiés." },
  { id: "ID.AM-4", category: "ID", subcategory: "AM", steps: [0],
    nl: "Externe informatiesystemen worden gecatalogiseerd.",
    en: "External information systems are catalogued.",
    fr: "Les systèmes d'information externes sont catalogués." },
  { id: "ID.AM-5", category: "ID", subcategory: "AM", steps: [0],
    nl: "Middelen worden geprioriteerd op basis van hun classificatie, kriticiteit en bedrijfswaarde.",
    en: "Resources are prioritized based on their classification, criticality, and business value.",
    fr: "Les ressources sont priorisées en fonction de leur classification, criticité et valeur métier." },
  { id: "ID.AM-6", category: "ID", subcategory: "AM", steps: [0, 4],
    nl: "Rollen, verantwoordelijkheden en bevoegdheden op het gebied van cyberbeveiliging worden vastgesteld.",
    en: "Cybersecurity roles, responsibilities, and authorities are established for all personnel.",
    fr: "Les rôles, responsabilités et autorités en cybersécurité sont établis pour tout le personnel." },

  // Business Environment
  { id: "ID.BE-1", category: "ID", subcategory: "BE", steps: [1],
    nl: "De rol van de organisatie in de toeleveringsketen wordt vastgesteld en gecommuniceerd.",
    en: "The organization's role in the supply chain is identified and communicated.",
    fr: "Le rôle de l'organisation dans la chaîne d'approvisionnement est identifié et communiqué." },
  { id: "ID.BE-2", category: "ID", subcategory: "BE", steps: [1],
    nl: "De plaats van de organisatie in de kritieke infrastructuur wordt vastgesteld.",
    en: "The organization's place in critical infrastructure is identified and communicated.",
    fr: "La place de l'organisation dans l'infrastructure critique est identifiée et communiquée." },
  { id: "ID.BE-3", category: "ID", subcategory: "BE", steps: [1],
    nl: "Prioriteiten m.b.t. missie, doelstellingen en activiteiten worden vastgesteld.",
    en: "Priorities for mission, objectives, and activities are established and communicated.",
    fr: "Les priorités relatives à la mission, objectifs et activités sont établies et communiquées." },
  { id: "ID.BE-4", category: "ID", subcategory: "BE", steps: [1],
    nl: "Afhankelijkheden en kritieke functies voor levering van kritieke diensten zijn vastgesteld.",
    en: "Dependencies and critical functions for delivery of critical services are established.",
    fr: "Les dépendances et fonctions critiques pour la fourniture de services critiques sont établies." },
  { id: "ID.BE-5", category: "ID", subcategory: "BE", steps: [1],
    nl: "Weerbaarheidsvereisten ter ondersteuning van kritieke diensten worden vastgesteld.",
    en: "Resilience requirements to support delivery of critical services are established.",
    fr: "Les exigences de résilience pour la fourniture de services critiques sont établies." },

  // Governance
  { id: "ID.GV-1", category: "ID", subcategory: "GV", steps: [1, 2],
    nl: "Het cyberbeveiligingsbeleid van de organisatie wordt vastgesteld en gecommuniceerd.",
    en: "The organization's cybersecurity policy is established and communicated.",
    fr: "La politique de cybersécurité de l'organisation est établie et communiquée." },
  { id: "ID.GV-3", category: "ID", subcategory: "GV", steps: [1, 2],
    nl: "Wettelijke en regelgevende voorschriften inzake cyberbeveiliging worden begrepen en beheerd.",
    en: "Legal and regulatory cybersecurity requirements, including privacy obligations, are understood and managed.",
    fr: "Les exigences légales et réglementaires en cybersécurité, y compris la vie privée, sont comprises et gérées." },
  { id: "ID.GV-4", category: "ID", subcategory: "GV", steps: [1],
    nl: "Governance- en risicobeheerprocessen adresseren risico's m.b.t. cyberbeveiliging.",
    en: "Governance and risk management processes address cybersecurity risks.",
    fr: "Les processus de gouvernance et de gestion des risques abordent les risques de cybersécurité." },

  // Risk Assessment
  { id: "ID.RA-1", category: "ID", subcategory: "RA", steps: [1],
    nl: "Kwetsbaarheden van activa worden vastgesteld en gedocumenteerd.",
    en: "Asset vulnerabilities are identified and documented.",
    fr: "Les vulnérabilités des actifs sont identifiées et documentées." },
  { id: "ID.RA-2", category: "ID", subcategory: "RA", steps: [1],
    nl: "Informatie over cyberdreigingen wordt ontvangen van fora en bronnen voor informatie-uitwisseling.",
    en: "Cyber threat intelligence is received from information sharing forums and sources.",
    fr: "Les renseignements sur les cybermenaces sont reçus de forums et sources de partage d'informations." },
  { id: "ID.RA-5", category: "ID", subcategory: "RA", steps: [1],
    nl: "Bedreigingen, kwetsbaarheden, waarschijnlijkheden en gevolgen worden gebruikt om het risico te bepalen.",
    en: "Threats, vulnerabilities, likelihoods, and impacts are used to determine risk.",
    fr: "Les menaces, vulnérabilités, probabilités et impacts sont utilisés pour déterminer le risque." },
  { id: "ID.RA-6", category: "ID", subcategory: "RA", steps: [1],
    nl: "Respons op risico's worden vastgesteld en geprioriteerd.",
    en: "Risk responses are identified and prioritized.",
    fr: "Les réponses aux risques sont identifiées et priorisées." },

  // Risk Management Strategy
  { id: "ID.RM-1", category: "ID", subcategory: "RM", steps: [1],
    nl: "Risicobeheerprocessen worden vastgesteld, beheerd en goedgekeurd door belanghebbenden.",
    en: "Risk management processes are established, managed, and agreed upon by stakeholders.",
    fr: "Les processus de gestion des risques sont établis, gérés et approuvés par les parties prenantes." },
  { id: "ID.RM-2", category: "ID", subcategory: "RM", steps: [1],
    nl: "De risicotolerantie van de organisatie wordt bepaald en duidelijk uitgedrukt.",
    en: "The organization's risk tolerance is determined and clearly expressed.",
    fr: "La tolérance au risque de l'organisation est déterminée et clairement exprimée." },
  { id: "ID.RM-3", category: "ID", subcategory: "RM", steps: [1],
    nl: "De organisatie bepaalt haar risicotolerantie op basis van haar rol in de kritieke infrastructuur.",
    en: "The organization determines its risk tolerance based on its role in critical infrastructure.",
    fr: "L'organisation détermine sa tolérance au risque en fonction de son rôle dans l'infrastructure critique." },

  // Supply Chain
  { id: "ID.SC-2", category: "ID", subcategory: "SC", steps: [5],
    nl: "Leveranciers en externe partners worden geïdentificeerd, geprioriteerd en beoordeeld.",
    en: "Suppliers and third-party partners are identified, prioritized, and assessed using a cyber supply chain risk assessment.",
    fr: "Les fournisseurs et partenaires tiers sont identifiés, priorisés et évalués via une évaluation des risques." },
  { id: "ID.SC-3", category: "ID", subcategory: "SC", steps: [5],
    nl: "Contracten met leveranciers bevatten passende cyberbeveiligingsmaatregelen.",
    en: "Contracts with suppliers include appropriate cybersecurity measures aligned with the organization's program.",
    fr: "Les contrats avec les fournisseurs incluent des mesures de cybersécurité appropriées." },
  { id: "ID.SC-4", category: "ID", subcategory: "SC", steps: [5],
    nl: "Leveranciers worden routinematig beoordeeld via audits of evaluaties.",
    en: "Suppliers are routinely assessed through audits, test results, or evaluations to confirm contractual compliance.",
    fr: "Les fournisseurs sont régulièrement évalués par des audits ou évaluations pour confirmer le respect contractuel." },
  { id: "ID.SC-5", category: "ID", subcategory: "SC", steps: [5],
    nl: "Respons- en herstelplanning en tests worden uitgevoerd met leveranciers.",
    en: "Response and recovery planning and testing are conducted with suppliers and third parties.",
    fr: "La planification et les tests de réponse et de reprise sont menés avec les fournisseurs et tiers." },

  // ===== BESCHERMEN (PR) =====
  // Access Control
  { id: "PR.AC-1", category: "PR", subcategory: "AC", steps: [2],
    nl: "Identiteiten en credentials worden afgegeven, beheerd, geverifieerd en gecontroleerd.",
    en: "Identities and credentials are issued, managed, verified, revoked, and audited for authorized devices and users.",
    fr: "Les identités et credentials sont émis, gérés, vérifiés, révoqués et audités." },
  { id: "PR.AC-2", category: "PR", subcategory: "AC", steps: [2],
    nl: "De fysieke toegang tot activa wordt beheerd en beschermd.",
    en: "Physical access to assets is managed and protected.",
    fr: "L'accès physique aux actifs est géré et protégé." },
  { id: "PR.AC-3", category: "PR", subcategory: "AC", steps: [2],
    nl: "De toegang op afstand wordt beheerd.",
    en: "Remote access is managed.",
    fr: "L'accès à distance est géré." },
  { id: "PR.AC-4", category: "PR", subcategory: "AC", steps: [2],
    nl: "Toegangsrechten worden beheerd met least privilege en scheiding van taken.",
    en: "Access permissions are managed incorporating least privilege and separation of duties.",
    fr: "Les droits d'accès sont gérés selon le moindre privilège et la séparation des tâches." },
  { id: "PR.AC-5", category: "PR", subcategory: "AC", steps: [2],
    nl: "Netwerkintegriteit (netwerksegregatie, netwerksegmentatie) wordt beschermd.",
    en: "Network integrity is protected (e.g., network segregation, network segmentation).",
    fr: "L'intégrité du réseau est protégée (ségrégation réseau, segmentation réseau)." },
  { id: "PR.AC-6", category: "PR", subcategory: "AC", steps: [2],
    nl: "Identiteiten worden aangetoond en verbonden aan credentials.",
    en: "Identities are proofed and bound to credentials and asserted in interactions.",
    fr: "Les identités sont vérifiées et liées aux credentials dans les interactions." },
  { id: "PR.AC-7", category: "PR", subcategory: "AC", steps: [2],
    nl: "Gebruikers, apparaten en andere activa worden geverifieerd op basis van risico.",
    en: "Users, devices, and other assets are authenticated commensurate with risk.",
    fr: "Les utilisateurs, appareils et actifs sont authentifiés en fonction du risque." },

  // Awareness & Training
  { id: "PR.AT-1", category: "PR", subcategory: "AT", steps: [4],
    nl: "Alle gebruikers worden geïnformeerd en opgeleid.",
    en: "All users are informed and trained.",
    fr: "Tous les utilisateurs sont informés et formés." },
  { id: "PR.AT-2", category: "PR", subcategory: "AT", steps: [4],
    nl: "Geprivilegieerde gebruikers begrijpen hun rollen en verantwoordelijkheden.",
    en: "Privileged users understand their roles and responsibilities.",
    fr: "Les utilisateurs privilégiés comprennent leurs rôles et responsabilités." },
  { id: "PR.AT-3", category: "PR", subcategory: "AT", steps: [4, 5],
    nl: "Belanghebbenden van derden begrijpen hun rol en verantwoordelijkheden.",
    en: "Third-party stakeholders understand their roles and responsibilities.",
    fr: "Les parties prenantes tierces comprennent leurs rôles et responsabilités." },
  { id: "PR.AT-4", category: "PR", subcategory: "AT", steps: [4],
    nl: "Hogere leidinggevenden begrijpen hun taken en verantwoordelijkheden.",
    en: "Senior executives understand their roles and responsibilities.",
    fr: "Les cadres supérieurs comprennent leurs rôles et responsabilités." },
  { id: "PR.AT-5", category: "PR", subcategory: "AT", steps: [4],
    nl: "Fysiek en cyberbeveiligingspersoneel begrijpt hun rollen.",
    en: "Physical and cybersecurity personnel understand their roles and responsibilities.",
    fr: "Le personnel de sécurité physique et cybersécurité comprend ses rôles et responsabilités." },

  // Data Security
  { id: "PR.DS-1", category: "PR", subcategory: "DS", steps: [2],
    nl: "Data in rust is beschermd.",
    en: "Data at rest is protected.",
    fr: "Les données au repos sont protégées." },
  { id: "PR.DS-2", category: "PR", subcategory: "DS", steps: [2],
    nl: "Data-in-transitie is beschermd.",
    en: "Data in transit is protected.",
    fr: "Les données en transit sont protégées." },
  { id: "PR.DS-3", category: "PR", subcategory: "DS", steps: [2],
    nl: "Activa worden formeel beheerd gedurende verhuizing, overdracht en verwijdering.",
    en: "Assets are formally managed throughout removal, transfers, and disposition.",
    fr: "Les actifs sont formellement gérés lors du retrait, transfert et mise au rebut." },
  { id: "PR.DS-4", category: "PR", subcategory: "DS", steps: [2],
    nl: "Voldoende capaciteit om de beschikbaarheid te waarborgen.",
    en: "Adequate capacity to ensure availability is maintained.",
    fr: "Une capacité adéquate est maintenue pour assurer la disponibilité." },
  { id: "PR.DS-5", category: "PR", subcategory: "DS", steps: [2],
    nl: "Beveiligingen tegen datalekken worden geïmplementeerd.",
    en: "Protections against data leaks are implemented.",
    fr: "Des protections contre les fuites de données sont mises en œuvre." },
  { id: "PR.DS-6", category: "PR", subcategory: "DS", steps: [2],
    nl: "Integriteitscontrolemechanismen worden gebruikt om software en informatie te controleren.",
    en: "Integrity checking mechanisms are used to verify software, firmware, and information integrity.",
    fr: "Des mécanismes de contrôle d'intégrité sont utilisés pour vérifier l'intégrité des logiciels et informations." },
  { id: "PR.DS-7", category: "PR", subcategory: "DS", steps: [2],
    nl: "De ontwikkelings- en testomgevingen zijn gescheiden van de productieomgeving.",
    en: "Development and testing environments are separate from the production environment.",
    fr: "Les environnements de développement et de test sont séparés de l'environnement de production." },

  // Information Protection Processes
  { id: "PR.IP-1", category: "PR", subcategory: "IP", steps: [2],
    nl: "Basisconfiguratie van IT-systemen wordt gecreëerd en onderhouden met beveiligingsbeginselen.",
    en: "A baseline configuration of IT systems is created and maintained incorporating security principles.",
    fr: "Une configuration de base des systèmes IT est créée et maintenue intégrant les principes de sécurité." },
  { id: "PR.IP-2", category: "PR", subcategory: "IP", steps: [2],
    nl: "Een levenscyclus voor systeemontwikkeling wordt geïmplementeerd.",
    en: "A System Development Life Cycle to manage systems is implemented.",
    fr: "Un cycle de vie de développement système est mis en œuvre pour gérer les systèmes." },
  { id: "PR.IP-3", category: "PR", subcategory: "IP", steps: [2],
    nl: "Er zijn processen voor het beheer van configuratiewijzigingen aanwezig.",
    en: "Configuration change control processes are in place.",
    fr: "Des processus de contrôle des modifications de configuration sont en place." },
  { id: "PR.IP-4", category: "PR", subcategory: "IP", steps: [2],
    nl: "Er worden back-ups van informatie gemaakt, onderhouden en getest.",
    en: "Backups of information are conducted, maintained, and tested.",
    fr: "Des sauvegardes d'information sont effectuées, maintenues et testées." },
  { id: "PR.IP-5", category: "PR", subcategory: "IP", steps: [2],
    nl: "Beleid m.b.t. de fysieke bedrijfsomgeving voor bedrijfsmiddelen wordt nageleefd.",
    en: "Policy regarding the physical operating environment for organizational assets is met.",
    fr: "La politique relative à l'environnement physique d'exploitation des actifs est respectée." },
  { id: "PR.IP-6", category: "PR", subcategory: "IP", steps: [2],
    nl: "Gegevens worden vernietigd overeenkomstig beleid.",
    en: "Data is destroyed according to policy.",
    fr: "Les données sont détruites conformément à la politique." },
  { id: "PR.IP-7", category: "PR", subcategory: "IP", steps: [6],
    nl: "De beschermingsprocessen worden verbeterd.",
    en: "Protection processes are improved.",
    fr: "Les processus de protection sont améliorés." },
  { id: "PR.IP-8", category: "PR", subcategory: "IP", steps: [6],
    nl: "De doeltreffendheid van beschermingstechnologieën wordt gedeeld.",
    en: "Effectiveness of protection technologies is shared.",
    fr: "L'efficacité des technologies de protection est partagée." },
  { id: "PR.IP-9", category: "PR", subcategory: "IP", steps: [3],
    nl: "Responsplannen en herstelplannen zijn aanwezig en worden beheerd.",
    en: "Response plans (Incident Response and Business Continuity) and recovery plans are in place and managed.",
    fr: "Les plans de réponse et de reprise sont en place et gérés." },
  { id: "PR.IP-11", category: "PR", subcategory: "IP", steps: [4],
    nl: "Cyberbeveiliging is opgenomen in het personeelsbeheer.",
    en: "Cybersecurity is included in human resources practices.",
    fr: "La cybersécurité est intégrée dans les pratiques de ressources humaines." },
  { id: "PR.IP-12", category: "PR", subcategory: "IP", steps: [6],
    nl: "Een plan voor het beheer van kwetsbaarheden wordt ontwikkeld en uitgevoerd.",
    en: "A vulnerability management plan is developed and implemented.",
    fr: "Un plan de gestion des vulnérabilités est développé et mis en œuvre." },

  // Maintenance
  { id: "PR.MA-1", category: "PR", subcategory: "MA", steps: [2],
    nl: "Onderhoud en reparatie worden uitgevoerd en geregistreerd met goedgekeurde gereedschappen.",
    en: "Maintenance and repair are performed and logged with approved and controlled tools.",
    fr: "La maintenance et les réparations sont effectuées et enregistrées avec des outils approuvés et contrôlés." },
  { id: "PR.MA-2", category: "PR", subcategory: "MA", steps: [2],
    nl: "Onderhoud op afstand wordt goedgekeurd, geregistreerd en voorkomt ongeoorloofde toegang.",
    en: "Remote maintenance is approved, logged, and performed in a manner that prevents unauthorized access.",
    fr: "La maintenance à distance est approuvée, enregistrée et réalisée de manière à prévenir l'accès non autorisé." },

  // Protective Technology
  { id: "PR.PT-1", category: "PR", subcategory: "PT", steps: [6],
    nl: "Registraties van audits/logs worden vastgesteld en herzien overeenkomstig beleid.",
    en: "Audit/log records are determined, documented, implemented, and reviewed in accordance with policy.",
    fr: "Les registres d'audit/journaux sont déterminés, documentés, mis en œuvre et révisés conformément à la politique." },
  { id: "PR.PT-2", category: "PR", subcategory: "PT", steps: [2],
    nl: "Verwisselbare media worden beschermd en het gebruik ervan wordt beperkt.",
    en: "Removable media is protected and its use restricted according to policy.",
    fr: "Les supports amovibles sont protégés et leur utilisation est restreinte conformément à la politique." },
  { id: "PR.PT-3", category: "PR", subcategory: "PT", steps: [2],
    nl: "Het beginsel van minimale functionaliteit wordt toegepast.",
    en: "The principle of least functionality is incorporated by configuring systems to provide only essential capabilities.",
    fr: "Le principe de fonctionnalité minimale est appliqué en configurant les systèmes pour ne fournir que les capacités essentielles." },
  { id: "PR.PT-4", category: "PR", subcategory: "PT", steps: [2],
    nl: "Communicatie- en besturingsnetwerken zijn beveiligd.",
    en: "Communications and control networks are protected.",
    fr: "Les réseaux de communication et de contrôle sont protégés." },

  // ===== DETECTEREN (DE) =====
  // Anomalies & Events
  { id: "DE.AE-2", category: "DE", subcategory: "AE", steps: [6],
    nl: "Gedetecteerde events worden geanalyseerd om aanvalsdoelen en -methoden te begrijpen.",
    en: "Detected events are analyzed to understand attack targets and methods.",
    fr: "Les événements détectés sont analysés pour comprendre les cibles et méthodes d'attaque." },
  { id: "DE.AE-3", category: "DE", subcategory: "AE", steps: [6],
    nl: "Gegevens m.b.t. events worden verzameld en gecorreleerd uit meerdere bronnen.",
    en: "Event data are collected and correlated from multiple sources and sensors.",
    fr: "Les données d'événements sont collectées et corrélées à partir de multiples sources et capteurs." },
  { id: "DE.AE-5", category: "DE", subcategory: "AE", steps: [6],
    nl: "Er worden alarmdrempels voor incidenten vastgesteld.",
    en: "Incident alert thresholds are established.",
    fr: "Des seuils d'alerte d'incidents sont établis." },

  // Continuous Monitoring
  { id: "DE.CM-1", category: "DE", subcategory: "CM", steps: [6],
    nl: "Het netwerk wordt bewaakt om potentiële cyberbeveiligingsevents op te sporen.",
    en: "The network is monitored to detect potential cybersecurity events.",
    fr: "Le réseau est surveillé pour détecter les événements potentiels de cybersécurité." },
  { id: "DE.CM-2", category: "DE", subcategory: "CM", steps: [6],
    nl: "De fysieke omgeving wordt bewaakt om potentiële cyberbeveiligingsgebeurtenissen op te sporen.",
    en: "The physical environment is monitored to detect potential cybersecurity events.",
    fr: "L'environnement physique est surveillé pour détecter les événements potentiels de cybersécurité." },
  { id: "DE.CM-3", category: "DE", subcategory: "CM", steps: [6],
    nl: "Personeelsactiviteiten worden gemonitord om potentiële cyberbeveiligingsgebeurtenissen op te sporen.",
    en: "Personnel activity is monitored to detect potential cybersecurity events.",
    fr: "L'activité du personnel est surveillée pour détecter les événements potentiels de cybersécurité." },
  { id: "DE.CM-4", category: "DE", subcategory: "CM", steps: [6],
    nl: "Kwaadaardige code wordt gedetecteerd.",
    en: "Malicious code is detected.",
    fr: "Le code malveillant est détecté." },
  { id: "DE.CM-5", category: "DE", subcategory: "CM", steps: [6],
    nl: "Ongeoorloofde mobiele code wordt gedetecteerd.",
    en: "Unauthorized mobile code is detected.",
    fr: "Le code mobile non autorisé est détecté." },
  { id: "DE.CM-6", category: "DE", subcategory: "CM", steps: [5, 6],
    nl: "De activiteit van externe dienstverleners wordt gemonitord.",
    en: "External service provider activity is monitored to detect potential cybersecurity events.",
    fr: "L'activité des prestataires de services externes est surveillée pour détecter les événements de cybersécurité." },
  { id: "DE.CM-7", category: "DE", subcategory: "CM", steps: [6],
    nl: "Monitoring op onbevoegd personeel, verbindingen, apparatuur en software.",
    en: "Monitoring for unauthorized personnel, connections, devices, and software is performed.",
    fr: "La surveillance du personnel, connexions, appareils et logiciels non autorisés est effectuée." },
  { id: "DE.CM-8", category: "DE", subcategory: "CM", steps: [6],
    nl: "Kwetsbaarheidsscans worden uitgevoerd.",
    en: "Vulnerability scans are performed.",
    fr: "Des analyses de vulnérabilités sont effectuées." },

  // Detection Processes
  { id: "DE.DP-2", category: "DE", subcategory: "DP", steps: [6],
    nl: "Detectie moet gebeuren conform alle toepasselijke eisen.",
    en: "Detection activities comply with all applicable requirements.",
    fr: "Les activités de détection sont conformes à toutes les exigences applicables." },
  { id: "DE.DP-3", category: "DE", subcategory: "DP", steps: [6],
    nl: "Detectieprocessen worden getest.",
    en: "Detection processes are tested.",
    fr: "Les processus de détection sont testés." },
  { id: "DE.DP-4", category: "DE", subcategory: "DP", steps: [3, 6],
    nl: "Informatie over gedetecteerde events wordt gecommuniceerd.",
    en: "Event detection information is communicated.",
    fr: "Les informations sur les événements détectés sont communiquées." },
  { id: "DE.DP-5", category: "DE", subcategory: "DP", steps: [6],
    nl: "De processen voor het detecteren van abnormale events worden voortdurend verbeterd.",
    en: "Detection processes are continuously improved.",
    fr: "Les processus de détection sont continuellement améliorés." },

  // ===== REAGEREN (RS) =====
  // Response Planning
  { id: "RS.RP-1", category: "RS", subcategory: "RP", steps: [3],
    nl: "Het responsplan wordt uitgevoerd tijdens of na een incident.",
    en: "Response plan is executed during or after an incident.",
    fr: "Le plan de réponse est exécuté pendant ou après un incident." },

  // Communications
  { id: "RS.CO-1", category: "RS", subcategory: "CO", steps: [3],
    nl: "Het personeel kent zijn rol en volgorde van handelen wanneer een reactie nodig is.",
    en: "Personnel know their role and order of operations when a response is needed.",
    fr: "Le personnel connaît son rôle et l'ordre des opérations lorsqu'une réponse est nécessaire." },
  { id: "RS.CO-2", category: "RS", subcategory: "CO", steps: [3],
    nl: "Incidenten worden gemeld overeenkomstig de vastgestelde criteria.",
    en: "Incidents are reported consistent with established criteria.",
    fr: "Les incidents sont signalés conformément aux critères établis." },
  { id: "RS.CO-3", category: "RS", subcategory: "CO", steps: [3],
    nl: "Informatie wordt gedeeld in overeenstemming met de responsplannen.",
    en: "Information is shared consistent with response plans.",
    fr: "L'information est partagée conformément aux plans de réponse." },
  { id: "RS.CO-4", category: "RS", subcategory: "CO", steps: [3],
    nl: "Coördinatie met belanghebbenden vindt plaats conform de responsplannen.",
    en: "Coordination with stakeholders occurs consistent with response plans.",
    fr: "La coordination avec les parties prenantes a lieu conformément aux plans de réponse." },
  { id: "RS.CO-5", category: "RS", subcategory: "CO", steps: [3],
    nl: "Vrijwillige informatie-uitwisseling met externe belanghebbenden voor breder situationeel bewustzijn.",
    en: "Voluntary information sharing occurs with external stakeholders to achieve broader cybersecurity situational awareness.",
    fr: "Le partage volontaire d'informations avec les parties prenantes externes pour une meilleure conscience situationnelle." },

  // Analysis
  { id: "RS.AN-1", category: "RS", subcategory: "AN", steps: [3],
    nl: "Meldingen van detectiesystemen worden onderzocht.",
    en: "Notifications from detection systems are investigated.",
    fr: "Les notifications des systèmes de détection sont examinées." },
  { id: "RS.AN-2", category: "RS", subcategory: "AN", steps: [3],
    nl: "De gevolgen van het incident worden begrepen.",
    en: "The impact of the incident is understood.",
    fr: "L'impact de l'incident est compris." },
  { id: "RS.AN-4", category: "RS", subcategory: "AN", steps: [3],
    nl: "Incidenten worden in categorieën ingedeeld overeenkomstig de responsplannen.",
    en: "Incidents are categorized consistent with response plans.",
    fr: "Les incidents sont catégorisés conformément aux plans de réponse." },
  { id: "RS.AN-5", category: "RS", subcategory: "AN", steps: [3],
    nl: "Processen voor het ontvangen, analyseren en reageren op kwetsbaarheden zijn vastgesteld.",
    en: "Processes are established for receiving, analyzing, and responding to disclosed vulnerabilities.",
    fr: "Des processus sont établis pour recevoir, analyser et répondre aux vulnérabilités divulguées." },

  // Mitigation
  { id: "RS.MI-1", category: "RS", subcategory: "MI", steps: [3],
    nl: "Incidenten worden beheerst.",
    en: "Incidents are contained.",
    fr: "Les incidents sont contenus." },

  // Improvements
  { id: "RS.IM-1", category: "RS", subcategory: "IM", steps: [3, 6],
    nl: "In de responsplannen zijn de geleerde lessen verwerkt.",
    en: "Response plans incorporate lessons learned.",
    fr: "Les plans de réponse intègrent les leçons apprises." },
  { id: "RS.IM-2", category: "RS", subcategory: "IM", steps: [3, 6],
    nl: "Reactie- en herstelstrategieën worden bijgewerkt.",
    en: "Response and recovery strategies are updated.",
    fr: "Les stratégies de réponse et de reprise sont mises à jour." },

  // ===== HERSTELLEN (RC) =====
  // Recovery Planning
  { id: "RC.RP-1", category: "RC", subcategory: "RP", steps: [3],
    nl: "Het herstelplan wordt uitgevoerd tijdens of na een cyberbeveiligingsincident.",
    en: "Recovery plan is executed during or after a cybersecurity incident.",
    fr: "Le plan de reprise est exécuté pendant ou après un incident de cybersécurité." },

  // Improvements
  { id: "RC.IM-1", category: "RC", subcategory: "IM", steps: [6],
    nl: "In de herstelplannen zijn de geleerde lessen verwerkt.",
    en: "Recovery plans incorporate lessons learned.",
    fr: "Les plans de reprise intègrent les leçons apprises." },

  // Communications
  { id: "RC.CO-1", category: "RC", subcategory: "CO", steps: [3],
    nl: "De public relations worden beheerd.",
    en: "Public relations are managed.",
    fr: "Les relations publiques sont gérées." },
  { id: "RC.CO-3", category: "RC", subcategory: "CO", steps: [3],
    nl: "Herstelactiviteiten worden gecommuniceerd aan interne en externe belanghebbenden.",
    en: "Recovery activities are communicated to internal and external stakeholders and executive management teams.",
    fr: "Les activités de reprise sont communiquées aux parties prenantes internes et externes et aux équipes de direction." },
];

export function getControlsByStep(stepIndex: number): CyFunControl[] {
  return CYFUN_CONTROLS.filter(c => c.steps.includes(stepIndex));
}

export function getControlsByCategory(category: string): CyFunControl[] {
  return CYFUN_CONTROLS.filter(c => c.category === category);
}

export function getControlText(control: CyFunControl, lang: Language): string {
  return control[lang];
}

export function getCategoryName(category: string, lang: Language): string {
  return CYFUN_CATEGORIES[category]?.[lang] ?? category;
}
