import type { PolicyFormData, PolicySection } from "./policy-templates";

export function generateEnglishSections(data: PolicyFormData): PolicySection[] {
  const generators: Record<string, (d: PolicyFormData) => PolicySection[]> = {
    access: (d) => [
      { heading: "1. Introduction", content: `${d.companyName} has established this access policy in the context of the NIS2 directive. This document describes how access to systems, networks and information is granted, managed and monitored.\n\nThis document was prepared by ${d.author} and approved by ${d.approvedBy} on ${d.date}.` },
      { heading: "2. Scope", content: `This policy applies to employees, external parties and suppliers who have access to ${d.companyName}'s systems or data. It covers both physical and digital access.` },
      { heading: "3. Core Principles", content: "1. Users receive only the rights necessary for their role.\n2. Access to information is granted only when needed for work.\n3. Critical tasks are divided among multiple people where possible.\n4. Every user must identify and authenticate before gaining access.\n5. Access rights are periodically reviewed and adjusted." },
      { heading: "4. User Management", content: "", subSections: [
        { heading: "4.1 New accounts", content: `New accounts are only created after approval by the responsible person within ${d.companyName}. Accounts are personal and may not be shared.` },
        { heading: "4.2 Change of rights", content: "When a role changes, existing rights are reviewed and adjusted to match the new role." },
        { heading: "4.3 End of collaboration", content: "When someone leaves or a collaboration ends, access is immediately revoked." },
      ]},
      { heading: "5. Passwords and Authentication", content: "1. Passwords are at least 12 characters long.\n2. They contain a mix of letters, numbers and special characters.\n3. Multi-factor authentication is used where required.\n4. Access to critical systems is additionally secured." },
      { heading: "6. Physical Access", content: `Buildings, workspaces and technical rooms of ${d.companyName} are protected against unauthorized access. Visitors are registered and escorted where necessary.` },
      { heading: "7. Logging and Monitoring", content: "Access attempts and relevant changes are logged. Suspicious activities are investigated and escalated when necessary." },
      { heading: "8. Incidents", content: `Any suspicion of misuse or unauthorized access is immediately reported according to ${d.companyName}'s internal procedure.` },
      { heading: "9. Review", content: "This policy is reviewed at least annually and updated when the organization, risks or legal requirements change." },
    ],
    network: (d) => [
      { heading: "1. Introduction", content: `${d.companyName} has established this network access policy in the context of the NIS2 directive. This document describes how network access is managed, secured and monitored.\n\nThis document was prepared by ${d.author} and approved by ${d.approvedBy} on ${d.date}.` },
      { heading: "2. Scope", content: `This policy applies to all networks, systems and devices connected to ${d.companyName}'s infrastructure. It applies to employees, guests and external parties.` },
      { heading: "3. Network Segmentation", content: `${d.companyName}'s network is divided into zones based on sensitivity and function. Traffic between zones is controlled via firewalls and access lists. Critical systems are placed in shielded segments.` },
      { heading: "4. Wireless Networks", content: "", subSections: [
        { heading: "4.1 Corporate network", content: "The corporate network is secured with WPA3 or equivalent. Only authorized devices gain access after authentication." },
        { heading: "4.2 Guest network", content: "Guests only receive access to a separate network segment without connection to internal systems." },
        { heading: "4.3 Device registration", content: "All devices connecting to the network are registered. Unknown devices are automatically blocked or quarantined." },
      ]},
      { heading: "5. External Connections", content: "1. VPN is used for remote access.\n2. External connections are encrypted with current protocols.\n3. Remote access requires multi-factor authentication.\n4. Sessions are automatically terminated after inactivity." },
      { heading: "6. Firewall and Filtering", content: `All incoming and outgoing traffic is filtered. By default, traffic is denied unless explicitly allowed. Firewall rules are periodically reviewed by ${d.companyName}'s IT team.` },
      { heading: "7. Monitoring", content: "Network traffic is continuously monitored for anomalies. Suspicious patterns are automatically detected and reported. Logs are retained for analysis and auditing." },
      { heading: "8. Incidents", content: `In the event of a suspected network breach, the incident is reported to the responsible person within ${d.companyName}. The affected segment may be temporarily isolated.` },
      { heading: "9. Review", content: "This policy is reviewed at least annually and updated upon changes in network infrastructure, threats or legislation." },
    ],
    incident: (d) => [
      { heading: "1. Introduction", content: `${d.companyName} has established this incident response policy in the context of the NIS2 directive. This document describes how cybersecurity incidents are detected, reported, managed and evaluated.\n\nThis document was prepared by ${d.author} and approved by ${d.approvedBy} on ${d.date}.` },
      { heading: "2. Scope", content: `This policy applies to all employees, systems and processes of ${d.companyName}. It applies to any security incident that may affect the confidentiality, integrity or availability of information.` },
      { heading: "3. Definition of an Incident", content: "A security incident is any event that jeopardizes the confidentiality, integrity or availability of information or systems. Examples include:\n1. Unauthorized access to systems or data.\n2. Malware infections or ransomware attacks.\n3. Data breaches or loss of sensitive information.\n4. Denial-of-service attacks.\n5. Phishing attacks with impact." },
      { heading: "4. Incident Classification", content: "", subSections: [
        { heading: "4.1 Severity levels", content: "Incidents are classified based on impact:\n- Critical: immediate threat to business continuity or large-scale data breach.\n- High: significant impact on systems or data, limited scope.\n- Medium: limited impact, no direct threat to core processes.\n- Low: minimal impact, easy to resolve." },
        { heading: "4.2 Escalation criteria", content: "Critical and high incidents are immediately escalated to management. For a significant incident, an initial report is made to the competent authority within 24 hours, followed by a full report within 72 hours, in accordance with NIS2 requirements." },
      ]},
      { heading: "5. Incident Response Process", content: "", subSections: [
        { heading: "5.1 Detection and reporting", content: `All employees of ${d.companyName} are required to immediately report suspicious activities to the designated contact person. Automated detection systems support early identification of incidents.` },
        { heading: "5.2 Assessment and triage", content: "After reporting, the incident is assessed for severity, scope and potential impact. Based on this, the appropriate response level is activated." },
        { heading: "5.3 Containment and recovery", content: "The incident is contained to prevent further damage. Then affected systems are restored to a safe state. All actions are documented." },
        { heading: "5.4 Evaluation and improvement", content: "After resolution, an evaluation is conducted to draw lessons. Findings are used to improve processes, systems and this policy." },
      ]},
      { heading: "6. Reporting Obligation", content: `${d.companyName} complies with the NIS2 reporting obligation:\n1. Initial report within 24 hours of detecting a significant incident.\n2. Full incident report within 72 hours.\n3. Final report within one month after resolution.\n\nReports are made to the competent national authority.` },
      { heading: "7. Roles and Responsibilities", content: `1. All employees: report suspicious activities.\n2. IT manager: coordinates the technical response.\n3. Management: decides on escalation and communication.\n4. ${d.approvedBy}: ultimately responsible for incident management.` },
      { heading: "8. Communication", content: "During an incident, internal communication occurs via predetermined channels. External communication (to customers, partners, authorities) is handled exclusively by management." },
      { heading: "9. Review", content: "This policy is reviewed at least annually and after each significant incident, evaluated and updated if necessary." },
    ],
    bcp: (d) => [
      { heading: "1. Introduction", content: `${d.companyName} has established this business continuity plan in the context of the NIS2 directive. This document describes how the organization continues to function during and after a disruption.\n\nThis document was prepared by ${d.author} and approved by ${d.approvedBy} on ${d.date}.` },
      { heading: "2. Scope", content: `This plan applies to all critical processes, systems and services of ${d.companyName}. It covers both IT systems and business processes essential to the organization's operations.` },
      { heading: "3. Critical Processes and Systems", content: `${d.companyName} identifies and documents the following critical elements:\n1. Business processes essential for service delivery.\n2. IT systems and applications supporting these processes.\n3. Dependencies on external suppliers and partners.\n4. Data indispensable for business operations.` },
      { heading: "4. Risk Analysis", content: "", subSections: [
        { heading: "4.1 Threats", content: "The following threats are considered:\n- Cyberattacks (ransomware, DDoS, data breaches).\n- Technical failures (hardware, software, network).\n- Natural disasters and physical damage.\n- Supplier or utility outages.\n- Human errors." },
        { heading: "4.2 Impact and recovery times", content: "For each critical process, the following are determined:\n- Recovery Time Objective (RTO): maximum acceptable downtime.\n- Recovery Point Objective (RPO): maximum acceptable data loss.\n- Minimum service level during a disruption." },
      ]},
      { heading: "5. Continuity Strategies", content: "1. Redundancy of critical systems and infrastructure.\n2. Regular backups per the backup policy.\n3. Alternative work locations or remote work facilities.\n4. Fallback procedures for essential services.\n5. Emergency communication channels for internal and external communication." },
      { heading: "6. Emergency Procedures", content: "", subSections: [
        { heading: "6.1 Activation", content: `The continuity plan is activated when a disruption significantly affects ${d.companyName}'s normal operations. The decision to activate is made by management.` },
        { heading: "6.2 Crisis team", content: "Upon activation, a crisis team is assembled responsible for:\n- Coordinating the response.\n- Communicating with stakeholders.\n- Monitoring the recovery process.\n- Decision-making on priorities." },
        { heading: "6.3 Recovery", content: "The recovery process follows a predetermined order based on the priority of processes and systems. Progress is continuously monitored and reported." },
      ]},
      { heading: "7. Testing and Exercising", content: `${d.companyName} tests this plan at least annually through:\n1. Tabletop exercises with the crisis team.\n2. Technical recovery tests of backups and systems.\n3. Evaluation of results and adjustments where needed.` },
      { heading: "8. Roles and Responsibilities", content: `1. Management: ultimately responsible for business continuity.\n2. IT manager: technical recovery of systems.\n3. Department heads: continuity of their business processes.\n4. ${d.approvedBy}: approval and oversight of the plan.` },
      { heading: "9. Review", content: "This plan is reviewed at least annually and updated upon changes in the organization, infrastructure, risks or legislation." },
    ],
    risk: (d) => [
      { heading: "1. Introduction", content: `${d.companyName} has established this risk management policy in the context of the NIS2 directive. This document describes how cyber risks are identified, assessed, treated and monitored.\n\nThis document was prepared by ${d.author} and approved by ${d.approvedBy} on ${d.date}.` },
      { heading: "2. Scope", content: `This policy applies to all information systems, networks, processes and data of ${d.companyName}. It applies to all employees and external parties.` },
      { heading: "3. Risk Management Process", content: "", subSections: [
        { heading: "3.1 Risk identification", content: `${d.companyName} systematically identifies risks through:\n- Inventory of critical assets and systems.\n- Analysis of threats and vulnerabilities.\n- Assessment of internal and external factors.\n- Consultation of relevant sources and threat intelligence.` },
        { heading: "3.2 Risk assessment", content: "Each risk is assessed on:\n- Likelihood of occurrence (low, medium, high).\n- Impact on the organization (low, medium, high, critical).\n- The combination determines the risk score and priority." },
        { heading: "3.3 Risk treatment", content: "For each risk, a treatment strategy is chosen:\n- Avoid: stop the activity causing the risk.\n- Reduce: take measures to lower likelihood or impact.\n- Transfer: transfer the risk to a third party (e.g. insurance).\n- Accept: consciously accept the risk with management approval." },
      ]},
      { heading: "4. Risk Register", content: `${d.companyName} maintains a risk register documenting all identified risks, their assessment, treatment strategy and status. This register is regularly updated.` },
      { heading: "5. Measures", content: "Based on the risk assessment, appropriate measures are taken:\n1. Technical measures (firewalls, encryption, access control).\n2. Organizational measures (procedures, training, awareness).\n3. Physical measures (access security, fire prevention).\n4. Contractual measures (SLAs, data processing agreements)." },
      { heading: "6. Monitoring and Reporting", content: "1. Risks are continuously monitored for changes.\n2. Quarterly risk status reporting to management.\n3. Immediate reporting of new significant risks.\n4. Annual complete risk assessment." },
      { heading: "7. Roles and Responsibilities", content: `1. ${d.approvedBy}: ultimately responsible for risk management.\n2. IT manager: identification and treatment of technical risks.\n3. All employees: reporting potential risks and vulnerabilities.\n4. Management: approval of risk treatment strategies.` },
      { heading: "8. Review", content: "This policy is reviewed at least annually and updated upon changes in the organization, threat landscape or legislation." },
    ],
    "supply-chain": (d) => [
      { heading: "1. Introduction", content: `${d.companyName} has established this supplier management policy in the context of the NIS2 directive. This document describes how the organization manages cybersecurity risks in the supply chain.\n\nThis document was prepared by ${d.author} and approved by ${d.approvedBy} on ${d.date}.` },
      { heading: "2. Scope", content: `This policy applies to all suppliers, service providers and partners who have access to ${d.companyName}'s systems, networks or data, or who deliver products or services that may affect the organization's cybersecurity.` },
      { heading: "3. Supplier Selection", content: "When selecting suppliers, the following is considered:\n1. The supplier's cybersecurity level.\n2. Certifications and security standards (e.g. ISO 27001).\n3. References and track record in security.\n4. Willingness to comply with the organization's security requirements." },
      { heading: "4. Contractual Requirements", content: "", subSections: [
        { heading: "4.1 Security requirements", content: `Contracts with ${d.companyName}'s suppliers contain at minimum:\n- Security requirements and standards to be met.\n- Obligation to report security incidents.\n- Right to audit and inspect.\n- Confidentiality obligations.` },
        { heading: "4.2 Data processing agreements", content: "When suppliers process personal data, a data processing agreement is concluded in accordance with GDPR. This includes agreements on security measures, sub-processors and data breach notification." },
      ]},
      { heading: "5. Supplier Monitoring", content: `${d.companyName} monitors suppliers on:\n1. Compliance with contractual security requirements.\n2. Security incidents at the supplier.\n3. Changes in risk profile.\n4. Continuity of service delivery.` },
      { heading: "6. Risk Assessment", content: "Suppliers are classified based on risk:\n- High risk: direct access to critical systems or sensitive data.\n- Medium risk: indirect access or delivery of important services.\n- Low risk: limited interaction without system access.\n\nThe frequency and depth of monitoring are aligned with the risk level." },
      { heading: "7. Supplier Incidents", content: `Suppliers are required to immediately report security incidents that may affect ${d.companyName}. ${d.companyName} includes such reports in its own incident response process.` },
      { heading: "8. Termination of Collaboration", content: "Upon termination of a collaboration:\n1. All access is revoked.\n2. Data is retrieved or destroyed.\n3. Confidentiality obligations are confirmed.\n4. Transfer agreements are fulfilled." },
      { heading: "9. Review", content: "This policy is reviewed at least annually and updated upon changes in supplier relationships, risks or legislation." },
    ],
    crypto: (d) => [
      { heading: "1. Introduction", content: `${d.companyName} has established this cryptography and encryption policy in the context of the NIS2 directive. This document describes how cryptographic measures are used to protect data.\n\nThis document was prepared by ${d.author} and approved by ${d.approvedBy} on ${d.date}.` },
      { heading: "2. Scope", content: `This policy applies to all systems, applications and communication channels of ${d.companyName} in which confidential or sensitive data is processed, stored or transmitted.` },
      { heading: "3. Core Principles", content: "1. Confidential data is encrypted at rest and in transit.\n2. Only recognized and current cryptographic algorithms are used.\n3. Key management is separated from data storage.\n4. Cryptographic measures are aligned with the data classification level." },
      { heading: "4. Encryption in Transit", content: "", subSections: [
        { heading: "4.1 Network traffic", content: "All traffic over public networks is encrypted with TLS 1.2 or higher. Deprecated protocols (SSL, TLS 1.0/1.1) are not supported." },
        { heading: "4.2 Email", content: "Sensitive email communication is encrypted. Employees are instructed on the use of encrypted email when required." },
        { heading: "4.3 File transfer", content: "Files with confidential content are sent exclusively via encrypted channels (SFTP, HTTPS)." },
      ]},
      { heading: "5. Encryption at Rest", content: "1. Hard drives of laptops and mobile devices are fully encrypted.\n2. Databases with sensitive data use field- or table-level encryption.\n3. Backups are stored encrypted.\n4. USB drives and external storage media are encrypted." },
      { heading: "6. Key Management", content: `${d.companyName} maintains the following key management rules:\n1. Cryptographic keys are securely generated with sufficient length.\n2. Keys are stored in secured key vaults.\n3. Access to keys is limited to authorized persons.\n4. Keys are periodically rotated.\n5. Expired or compromised keys are immediately revoked.` },
      { heading: "7. Algorithms and Standards", content: "The following minimum standards apply:\n- Symmetric encryption: AES-256.\n- Asymmetric encryption: RSA-2048 or higher, or elliptic curve cryptography.\n- Hashing: SHA-256 or higher.\n- Protocols are evaluated annually against current guidelines." },
      { heading: "8. Review", content: "This policy is reviewed at least annually and updated upon changes in technology, threats or legal requirements." },
    ],
    awareness: (d) => [
      { heading: "1. Introduction", content: `${d.companyName} has established this awareness and training policy in the context of the NIS2 directive. This document describes how employees are trained and made aware of cybersecurity risks.\n\nThis document was prepared by ${d.author} and approved by ${d.approvedBy} on ${d.date}.` },
      { heading: "2. Scope", content: `This policy applies to all employees of ${d.companyName}, including temporary staff, interns and external workers who have access to systems or data.` },
      { heading: "3. Objectives", content: "1. Make employees aware of cyber threats and their role in security.\n2. Teach knowledge and skills for secure working.\n3. Create a security culture where everyone takes responsibility.\n4. Comply with the NIS2 requirement for awareness programs." },
      { heading: "4. Awareness Program", content: "", subSections: [
        { heading: "4.1 Onboarding", content: `New employees of ${d.companyName} receive an introduction upon joining about:\n- The information security policy.\n- Safe use of passwords and systems.\n- Recognizing phishing and social engineering.\n- Reporting procedures for suspicious situations.` },
        { heading: "4.2 Periodic training", content: "All employees complete at least annual cybersecurity training. Topics are aligned with current threats and the employee's role." },
        { heading: "4.3 Phishing simulations", content: "Periodic phishing simulations are conducted to test awareness. Results are used to offer targeted training." },
      ]},
      { heading: "5. Specific Training", content: "In addition to general awareness, specific training is offered for:\n1. IT administrators: technical security measures and incident response.\n2. Management: risk management and responsibilities under NIS2.\n3. Employees with access to sensitive data: data classification and protection." },
      { heading: "6. Communication", content: `${d.companyName} regularly communicates about cybersecurity via:\n1. Internal newsletters or messages about current threats.\n2. Tips and guidelines for secure working.\n3. Feedback on phishing simulation results.\n4. Updates on policy or procedure changes.` },
      { heading: "7. Registration and Evaluation", content: "1. Training attendance is registered.\n2. Effectiveness is measured via tests and simulations.\n3. Results are reported to management.\n4. The program is adjusted based on evaluations." },
      { heading: "8. Review", content: "This policy is reviewed at least annually and updated for new threats, organizational changes or legal requirements." },
    ],
    vulnerability: (d) => [
      { heading: "1. Introduction", content: `${d.companyName} has established this vulnerability management policy in the context of the NIS2 directive. This document describes how vulnerabilities in systems and software are identified, assessed and remediated.\n\nThis document was prepared by ${d.author} and approved by ${d.approvedBy} on ${d.date}.` },
      { heading: "2. Scope", content: `This policy applies to all IT systems, applications, network equipment and software of ${d.companyName}, both internally managed and outsourced.` },
      { heading: "3. Vulnerability Identification", content: `${d.companyName} identifies vulnerabilities through:\n1. Regular vulnerability scans of systems and networks.\n2. Monitoring security advisories from vendors and CERTs.\n3. Penetration tests (at least annually for critical systems).\n4. Assessment of new threat intelligence.` },
      { heading: "4. Assessment and Prioritization", content: "", subSections: [
        { heading: "4.1 Severity score", content: "Vulnerabilities are assessed based on:\n- CVSS score (Common Vulnerability Scoring System).\n- Impact on the organization.\n- Exploitability and availability of exploits.\n- Exposure of the affected system." },
        { heading: "4.2 Remediation timelines", content: "Based on the assessment, the following timelines apply:\n- Critical: within 24-48 hours.\n- High: within 1 week.\n- Medium: within 1 month.\n- Low: at the next maintenance cycle." },
      ]},
      { heading: "5. Patch Management", content: "1. Security patches are tested and deployed as quickly as possible.\n2. Patches for critical systems take priority.\n3. Patches are tested in a test environment before production rollout.\n4. When a patch is not possible, compensating measures are taken.\n5. The patching process is documented." },
      { heading: "6. Exceptions", content: `When a vulnerability cannot be remediated within the set timeline, a justified exception is recorded. This must be approved by ${d.approvedBy} and contains:\n- Reason for the exception.\n- Compensating measures.\n- Planned remediation date.\n- Risk acceptance.` },
      { heading: "7. Reporting", content: "1. Monthly overview of open vulnerabilities.\n2. Status of patch implementation.\n3. Results of vulnerability scans and penetration tests.\n4. Reporting to management for critical vulnerabilities." },
      { heading: "8. Review", content: "This policy is reviewed at least annually and updated upon changes in infrastructure, new threats or legal requirements." },
    ],
    backup: (d) => [
      { heading: "1. Introduction", content: `${d.companyName} has established this backup and recovery policy in the context of the NIS2 directive. This document describes how data is backed up, stored and restored.\n\nThis document was prepared by ${d.author} and approved by ${d.approvedBy} on ${d.date}.` },
      { heading: "2. Scope", content: `This policy applies to all data, systems and applications of ${d.companyName} that are essential for business operations.` },
      { heading: "3. Backup Strategy", content: "", subSections: [
        { heading: "3.1 Backup types", content: "The following backup types are used:\n- Full backup: periodic copy of all data.\n- Incremental backup: daily copy of changed data.\n- Differential backup: copy of all changes since the last full backup." },
        { heading: "3.2 Frequency", content: "1. Critical systems: daily backup (minimum).\n2. Important systems: weekly full backup with daily incremental backups.\n3. Other systems: weekly backup." },
        { heading: "3.3 Retention period", content: "1. Daily backups: retained for at least 30 days.\n2. Weekly backups: retained for at least 3 months.\n3. Monthly backups: retained for at least 1 year.\n4. Legally required data: per applicable retention periods." },
      ]},
      { heading: "4. Storage and Security", content: `1. Backups are stored at a physically separate location.\n2. All backups are encrypted per the cryptography policy.\n3. Access to backups is limited to authorized ${d.companyName} employees.\n4. Backup media are protected against physical damage and unauthorized access.` },
      { heading: "5. 3-2-1 Rule", content: `${d.companyName} follows the 3-2-1 rule:\n- 3 copies of each dataset (1 original + 2 backups).\n- 2 different storage media.\n- 1 copy at an external location (offsite or cloud).` },
      { heading: "6. Recovery Procedures", content: "", subSections: [
        { heading: "6.1 Recovery process", content: "In case of data loss, the following process is followed:\n1. Determination of the extent of loss.\n2. Selection of the appropriate backup based on the desired recovery point.\n3. Recovery in a controlled environment.\n4. Verification of recovered data integrity.\n5. Return to the production environment." },
        { heading: "6.2 Recovery tests", content: "Backups are tested at least quarterly by:\n- A full recovery test of selected systems.\n- Verification of the integrity and usability of recovered data.\n- Measurement of recovery time against the set RTO.\n- Documentation of test results." },
      ]},
      { heading: "7. Monitoring and Reporting", content: "1. Backup processes are monitored daily for successful execution.\n2. Errors are immediately investigated and resolved.\n3. Monthly backup status reporting to management.\n4. Annual evaluation of the backup strategy." },
      { heading: "8. Review", content: "This policy is reviewed at least annually and updated upon changes in infrastructure, data needs or legal requirements." },
    ],
  };
  return generators[data.policyType](data);
}
